</head>
<style>
    .activeDay {
        background-color: #ff0000 !important;
    }
</style>
<body>
<h2 style="padding-top: 0px; width: 100%;"><b>Mis Ideas de Negocio</h2>
<input type="hidden" id="hdnIdRelaboralUsuario" name="hdnIdRelaboralUsuario" value="<?php echo $idRelaboral; ?>">
<input type="hidden" id="hdnIdPersonaUsuario" name="hdnIdPersonaUsuario" value="<?php echo $idPersona; ?>">
<input type="hidden" id="hdnNombresUsuario" name="hdnNombresUsuario" value="<?php echo $nombres; ?>">
<input type="hidden" id="hdnCiUsuario" name="hdnciUsuario" value="<?php echo $ci; ?>">

<div id='divTabIdeas'>
<ul>
    <li id="liIdeas">Ideas</li>
    <li id="liNew">Nuevo</li>
    <li id="liEdit">Modificaci&oacute;n</li>
    <li id="liView">Ver</li>
</ul>
<br>

<div class="section" id="divIdeas">
    <form class="navbar-form" id="formExcept">
        <div id="tabFichaPersonalIdeas">
            <ul style="margin-left: 30px;">
                <li>Relaci&oacute;n Laboral</li>
                <li>Datos Personales</li>
                <li>Contacto Personal</li>
                <li>Contacto Institucional</li>
            </ul>
            <div class="form-horizontal col-sm-12">
                <br>

                <div class="widget">
                    <div class="widget-simple themed-background-dark">
                        <a href="#" id="aFotoPerfilTurnAndExceptRelaboral">
                            <img id="imgFotoPerfilTurnAndExceptRelaboral" class="img-rounded pull-right img-perfil">
                        </a>
                        <h4 class="widget-content">
                            <div class="col-sm-5">
                                <dl class="dl-horizontal" STYLE="color: white;font-size: 13px;">
                                    <dt class="dtNombresTurnAndExcept">Nombres:</dt>
                                    <dd class="ddNombresTurnAndExcept"></dd>
                                    <dt class="dtCIAndNumComplementoExpdTurnAndExcept">CI:</dt>
                                    <dd class="ddCIAndNumComplementoExpdTurnAndExcept"></dd>
                                    <dt id="dtCargoTurnAndExcept">Cargo:</dt>
                                    <dd id="ddCargoTurnAndExcept"></dd>
                                    <dt id="dtProcesoTurnAndExcept">Proceso:</dt>
                                    <dd id="ddProcesoTurnAndExcept"></dd>
                                    <dt id="dtFinanciamientoTurnAndExcept">Financiamiento:</dt>
                                    <dd id="ddFinanciamientoTurnAndExcept"></dd>
                                    <dt id="dtGerenciaTurnAndExcept">Gerencia:</dt>
                                    <dd id="ddGerenciaTurnAndExcept"></dd>
                                    <dt id="dtDepartamentoTurnAndExcept">Departamento:</dt>
                                    <dd id="ddDepartamentoTurnAndExcept"></dd>
                                </dl>
                            </div>
                            <div class="col-sm-5">
                                <dl class="dl-horizontal" STYLE="color: white;font-size: 13px;">
                                    <dt id="dtUbicacionTurnAndExcept">Ubicaci&oacute;n:</dt>
                                    <dd id="ddUbicacionTurnAndExcept"></dd>
                                    <dt id="dtItemTurnAndExcept">&Iacute;tem:</dt>
                                    <dd id="ddItemTurnAndExcept"></dd>
                                    <dt id="dtNivelSalarialTurnAndExcept">Nivel Salarial:</dt>
                                    <dd id="ddNivelSalarialTurnAndExcept"></dd>
                                    <dt id="dtHaberTurnAndExcept">Haber:</dt>
                                    <dd id="ddHaberTurnAndExcept"></dd>
                                    <dt id="dtFechaIngTurnAndExcept">Fecha Ingreso:</dt>
                                    <dd id="ddFechaIngTurnAndExcept"></dd>
                                    <dt id="dtFechaIniTurnAndExcept">Fecha Inicio:</dt>
                                    <dd id="ddFechaIniTurnAndExcept"></dd>
                                    <dt id="dtFechaIncorTurnAndExcept">Fecha Incorporaci&oacute;n:</dt>
                                    <dd id="ddFechaIncorTurnAndExcept"></dd>
                                    <dt id="dtFechaFinTurnAndExcept">Fecha Finalizaci&oacute;n:</dt>
                                    <dd id="ddFechaFinTurnAndExcept"></dd>
                                    <dt id="dtEstadoDescripcionTurnAndExcept">Estado:</dt>
                                    <dd id="ddEstadoDescripcionTurnAndExcept"></dd>
                                    <dt id="dtFechaBajaTurnAndExcept">Fecha Baja:</dt>
                                    <dd id="ddFechaBajaTurnAndExcept"></dd>
                                    <dt id="dtMotivoBajaTurnAndExcept">Motivo Baja:</dt>
                                    <dd id="ddMotivoBajaTurnAndExcept"></dd>
                                    <dt id="dtObservacionTurnAndExcept">Observaciones:</dt>
                                    <dd id="ddObservacionTurnAndExcept"></dd>
                                </dl>
                            </div>
                        </h4>
                    </div>
                </div>
            </div>
            <div class="form-horizontal col-sm-12">
                <br>

                <div class="widget">
                    <div class="widget-simple themed-background-dark">
                        <a href="#" id="aFotoPerfilTurnAndExcept">
                            <img id="imgFotoPerfilTurnAndExcept" class="img-rounded pull-right img-perfil">
                        </a>
                        <h4 class="widget-content">
                            <div>
                                <dl class="dl-horizontal" STYLE="color: white;font-size: 13px;">
                                    <dt id="dtNombresTurnAndExcept">Nombres y Apellidos:</dt>
                                    <dd id="ddNombresTurnAndExcept"></dd>
                                    <dt id="dtTipoDeDocumentoTurnAndExcept"></dt>
                                    <dd id="ddNumeroDeDocumentoTurnAndExcept"></dd>
                                    <dt id="dtNacionalidadTurnAndExcept">Nacionalidad:</dt>
                                    <dd id="ddNacionalidadTurnAndExcept"></dd>
                                    <dt id="dtLugarDeNacimientoTurnAndExcept">Lugar de Nacimiento:</dt>
                                    <dd id="ddLugarDeNacimientoTurnAndExcept"></dd>
                                    <dt id="dtFechaDeNacimientoTurnAndExcept">Fecha de Nacimiento:</dt>
                                    <dd id="ddFechaDeNacimientoTurnAndExcept"></dd>
                                </dl>
                            </div>
                        </h4>
                    </div>
                </div>
            </div>
            <div class="form-horizontal col-sm-12">
                <br>

                <div class="widget">
                    <div class="widget-simple themed-background-dark">
                        <a href="#" id="aFotoPerfilContactoPerTurnAndExcept"><img
                                id="imgFotoPerfilContactoPerTurnAndExcept"
                                class="img-rounded pull-right img-perfil"></a>
                        <h4 class="widget-content">
                            <div>
                                <dl class="dl-horizontal" STYLE="color: white;font-size: 13px;">
                                    <dt id="dtDireccionTurnAndExcept">Direcci&oacute;n:</dt>
                                    <dd id="ddDireccionTurnAndExcept"></dd>
                                    <dt id="dtTelefonoFijoTurnAndExcept">Tel&eacute;fono Fijo:</dt>
                                    <dd id="ddTelefonoFijoTurnAndExcept"></dd>
                                    <dt id="dtCelularPerTurnAndExcept">Celular Personal:</dt>
                                    <dd id="ddCelularPerTurnAndExcept"></dd>
                                    <dt id="dtEmailPerTurnAndExcept">E-Mail Personal:</dt>
                                    <dd id="ddEmailPerTurnAndExcept"></dd>
                                    <dt id="dtAuxiliar1TurnAndExcept">&nbsp;</dt>
                                    <dd id="ddAuxiliar1TurnAndExcept">&nbsp;</dd>
                                </dl>
                            </div>
                        </h4>
                    </div>
                </div>
            </div>
            <div class="form-horizontal col-sm-12">
                <br>

                <div class="widget">
                    <div class="widget-simple themed-background-dark">
                        <a href="#" id="aFotoPerfilContactoInstTurnAndExcept"><img
                                id="imgFotoPerfilContactoInstTurnAndExcept"
                                class="img-rounded pull-right img-perfil"></a>
                        <h4 class="widget-content">
                            <div>
                                <dl class="dl-horizontal" STYLE="color: white;font-size: 13px;">
                                    <dt id="dtTelefonoInstTurnAndExcept">Tel&eacute;fono Inst.:</dt>
                                    <dd id="ddTelefonoInstTurnAndExcept"></dd>
                                    <dt id="dtCelularInstTurnAndExcept">Celular Corporativo:</dt>
                                    <dd id="ddCelularInstTurnAndExcept"></dd>
                                    <dt id="dtTelefonoFaxTurnAndExcept">Fax:</dt>
                                    <dd id="ddTelefonoFaxTurnAndExcept"></dd>
                                    <dt id="dtInternoInstTurnAndExcept">N&uacute;mero Interno:</dt>
                                    <dd id="ddInternoInstTurnAndExcept"></dd>
                                    <dt id="dtEmailInstTurnAndExcept">E-Mail Institucional:</dt>
                                    <dd id="ddEmailInstTurnAndExcept"></dd>
                                </dl>
                            </div>
                        </h4>
                    </div>
                </div>
            </div>
        </div>
        <br>

        <div id="divGridIdeas"></div>
        <div>
        </div>
    </form>
</div>
<div class="section" id="divNew">
    <h6><b>NOTA: </b>Los datos precedidos de asterisco son requerido de manera obligatoria (*).</h6>

    <div class="form-horizontal col-sm-12">
        <fieldset>
            <legend><i class="fa fa-angle-right"></i> Detalle de la Idea de Negocio</legend>
            <!-- Headings Block -->
            <div class="row">
                <div class="div-ideas" id="divGestionNew">
                    <label class="col-sm-2 control-label" for="lstGestionNew">Gesti&oacute;n *:</label>

                    <div class="col-md-2">
                        <select id="lstGestionNew" class="form-control">
                            <option value="">Seleccionar..</option>
                        </select>
                        <span class="help-block" id="helpErrorGestionNew"></span>
                    </div>
                </div>
                <div class="div-ideas" id="divMesNew">
                    <label class="col-sm-2 control-label" for="lstMesNew">Mes *:</label>

                    <div class="col-md-2">
                        <select id="lstMesNew" class="form-control">
                            <option value="">Seleccionar..</option>
                        </select>
                        <span class="help-block" id="helpErrorMesNew"></span>
                    </div>
                </div>
                <div class="div-ideas" id="divTiposDeNegocioNew">
                    <label class="col-sm-2 control-label" for="lstTiposDeNegocioNew">Tipo *:</label>

                    <div class="col-md-2">
                        <select id="lstTiposDeNegocioNew" class="form-control">
                            <option value="">Seleccionar..</option>
                        </select>
                        <span class="help-block" id="helpErrorTiposDeNegocioNew"></span>
                    </div>
                </div>
            </div>
            <div class="form-group div-ideas" id="divTituloNew">
                <label class="col-md-3 control-label" for="txtTituloNew">T&iacute;tulo*:</label>

                <div class="col-md-6">
                    <textarea id="txtTituloNew" name="txtTituloNew" class="form-control"
                              placeholder="T&iacute;tulo de la Idea de Negocio.."></textarea>
                </div>
                <span class="help-block" id="helpErrorTituloNew"></span>
            </div>
            <div class="form-group div-ideas" id="divResumenNew">
                <label class="col-md-3 control-label" for="txtResumenNew">Resumen*:</label>

                <div class="col-md-6">
                    <textarea id="txtResumenNew" name="txtResumenNew" class="form-control"
                              placeholder="Resumen de la Idea de Negocio.."></textarea>
                </div>
                <span class="help-block" id="helpErrorResumenNew"></span>
            </div>
            <div class="form-group div-ideas" id="divDescripcionNew">
                <label class="col-md-3 control-label" for="txtDescripcionNew">Planteamiento*:</label>

                <div class="col-md-6">
                    <textarea id="txtDescripcionNew" name="txtDescripcionNew" class="form-control"
                              placeholder="Planteamiento de la Idea de Negocio.."></textarea>
                </div>
                <span class="help-block" id="helpErrorDescripcionNew"></span>
            </div>
        </fieldset>
        <fieldset>
            <legend><i class="fa fa-angle-right"></i> &nbsp;</legend>
            <div class="form-group div-control-excepciones" id="divObservacionNew">
                <label class="col-md-3 control-label" for="txtObservacionNew"
                       id="lblObservacionNew">Observaciones:</label>

                <div class="col-md-6">
                    <textarea id="txtObservacionNew" name="txtObservacionNew" class="form-control"
                              placeholder="Observaciones.."></textarea>
                </div>
                <span class="help-block" id="helpErrorObservacionNew"></span>
            </div>
        </fieldset>
        <div class="form-group form-actions">
            <div class="col-md-8 col-md-offset-4">
                <button id="btnGuardarIdeaNew" class="btn btn-sm btn-primary" type="button">
                    <i class="fa fa-floppy-o"></i>
                    Guardar
                </button>
                <button id="btnCancelarIdeaNew" class="btn btn-sm btn-warning" type="button">
                    <i class="fa fa-repeat"></i>
                    Cancelar
                </button>
                <button class="btn btn-sm btn-warning" type="button" id="btnVolverAlListadoPrincipalDesdeNew">
                    <i class="fa fa-reply"></i>
                    Volver al Listado Principal
                </button>
            </div>
        </div>
        <input type="hidden" id="hdnIdRelaboralNew" value="0">
    </div>
</div>
<div class="section" id="divEdit">
    <h6><b>NOTA: </b>Los datos precedidos de asterisco son requerido de manera obligatoria (*).</h6>

    <div class="form-horizontal col-sm-12">
        <fieldset>
            <legend><i class="fa fa-angle-right"></i> Detalle de la Idea de Negocio</legend>
            <!-- Headings Block -->
            <div class="row">
                <div class="div-ideas" id="divGestionEdit">
                    <label class="col-sm-2 control-label" for="lstGestionEdit">Gesti&oacute;n *:</label>

                    <div class="col-md-2">
                        <select id="lstGestionEdit" class="form-control">
                            <option value="">Seleccionar..</option>
                        </select>
                        <span class="help-block" id="helpErrorGestionEdit"></span>
                    </div>
                </div>
                <div class="div-ideas" id="divMesEdit">
                    <label class="col-sm-2 control-label" for="lstMesEdit">Mes *:</label>

                    <div class="col-md-2">
                        <select id="lstMesEdit" class="form-control">
                            <option value="">Seleccionar..</option>
                        </select>
                        <span class="help-block" id="helpErrorMesEdit"></span>
                    </div>
                </div>
                <div class="div-ideas" id="divTiposDeNegocioEdit">
                    <label class="col-sm-2 control-label" for="lstTiposDeNegocioEdit">Tipo *:</label>

                    <div class="col-md-2">
                        <select id="lstTiposDeNegocioEdit" class="form-control">
                            <option value="">Seleccionar..</option>
                        </select>
                        <span class="help-block" id="helpErrorTiposDeNegocioEdit"></span>
                    </div>
                </div>
            </div>
            <div class="form-group div-ideas" id="divTituloEdit">
                <label class="col-md-3 control-label" for="txtTituloEdit">T&iacute;tulo*:</label>

                <div class="col-md-6">
                    <textarea id="txtTituloEdit" name="txtTituloEdit" class="form-control"
                              placeholder="T&iacute;tulo de la Idea de Negocio.."></textarea>
                </div>
                <span class="help-block" id="helpErrorTituloEdit"></span>
            </div>
            <div class="form-group div-ideas" id="divResumenEdit">
                <label class="col-md-3 control-label" for="txtResumenEdit">Resumen*:</label>

                <div class="col-md-6">
                    <textarea id="txtResumenEdit" name="txtResumenEdit" class="form-control"
                              placeholder="Resumen de la Idea de Negocio.."></textarea>
                </div>
                <span class="help-block" id="helpErrorResumenEdit"></span>
            </div>
            <div class="form-group div-ideas" id="divDescripcionEdit">
                <label class="col-md-3 control-label" for="txtDescripcionEdit">Planteamiento*:</label>

                <div class="col-md-6">
                    <textarea id="txtDescripcionEdit" name="txtDescripcionEdit" class="form-control"
                              placeholder="Planteamiento de la Idea de Negocio.."></textarea>
                </div>
                <span class="help-block" id="helpErrorDescripcionEdit"></span>
            </div>
        </fieldset>
        <fieldset>
            <legend><i class="fa fa-angle-right"></i> &nbsp;</legend>
            <div class="form-group div-control-excepciones" id="divObservacionEdit">
                <label class="col-md-3 control-label" for="txtObservacionEdit"
                       id="lblObservacionEdit">Observaciones:</label>

                <div class="col-md-6">
                    <textarea id="txtObservacionEdit" name="txtObservacionEdit" class="form-control"
                              placeholder="Observaciones.."></textarea>
                </div>
                <span class="help-block" id="helpErrorObservacionEdit"></span>
            </div>
        </fieldset>
        <div class="form-group form-actions">
            <div class="col-md-8 col-md-offset-4">
                <button id="btnGuardarIdeaEdit" class="btn btn-sm btn-primary" type="button">
                    <i class="fa fa-floppy-o"></i>
                    Guardar
                </button>
                <button id="btnCancelarIdeaEdit" class="btn btn-sm btn-warning" type="button">
                    <i class="fa fa-repeat"></i>
                    Cancelar
                </button>
                <button class="btn btn-sm btn-warning" type="button" id="btnVolverAlListadoPrincipalDesdeEdit">
                    <i class="fa fa-reply"></i>
                    Volver al Listado Principal
                </button>
            </div>
        </div>
        <input type="hidden" id="hdnIdRelaboralEdit" value="0">
        <input type="hidden" id="hdnIdIdeaEdit" value="0">
    </div>
</div>
<div class="section" id="divView">
    <h6><b>NOTA: </b>Los datos precedidos de asterisco son requerido de manera obligatoria (*).</h6>

    <div class="form-horizontal col-sm-12">
        <fieldset>
            <legend><i class="fa fa-angle-right"></i> Detalle de la Idea de Negocio</legend>
            <!-- Headings Block -->
            <div class="row">
                <div class="div-ideas" id="divGestionView">
                    <label class="col-sm-2 control-label" for="lstGestionView">Gesti&oacute;n *:</label>

                    <div class="col-md-2">
                        <select id="lstGestionView" class="form-control">
                            <option value="">Seleccionar..</option>
                        </select>
                        <span class="help-block" id="helpErrorGestionView"></span>
                    </div>
                </div>
                <div class="div-ideas" id="divMesView">
                    <label class="col-sm-2 control-label" for="lstMesView">Mes *:</label>

                    <div class="col-md-2">
                        <select id="lstMesView" class="form-control">
                            <option value="">Seleccionar..</option>
                        </select>
                        <span class="help-block" id="helpErrorMesView"></span>
                    </div>
                </div>
                <div class="div-ideas" id="divTiposDeNegocioView">
                    <label class="col-sm-2 control-label" for="lstTiposDeNegocioView">Tipo *:</label>

                    <div class="col-md-2">
                        <select id="lstTiposDeNegocioView" class="form-control">
                            <option value="">Seleccionar..</option>
                        </select>
                        <span class="help-block" id="helpErrorTiposDeNegocioView"></span>
                    </div>
                </div>
            </div>
            <div class="form-group div-ideas" id="divTituloView">
                <label class="col-md-3 control-label" for="txtTituloView">T&iacute;tulo*:</label>

                <div class="col-md-6">
                    <textarea id="txtTituloView" name="txtTituloView" class="form-control"
                              placeholder="T&iacute;tulo de la Idea de Negocio.." readonly></textarea>
                </div>
                <span class="help-block" id="helpErrorTituloView"></span>
            </div>
            <div class="form-group div-ideas" id="divResumenView">
                <label class="col-md-3 control-label" for="txtResumenView">Resumen*:</label>

                <div class="col-md-6">
                    <textarea id="txtResumenView" name="txtResumenView" class="form-control"
                              placeholder="Resumen de la Idea de Negocio.." readonly></textarea>
                </div>
                <span class="help-block" id="helpErrorResumenView"></span>
            </div>
            <div class="form-group div-ideas" id="divDescripcionView">
                <label class="col-md-3 control-label" for="txtDescripcionView">Planteamiento*:</label>

                <div class="col-md-6">
                    <textarea id="txtDescripcionView" name="txtDescripcionView" class="form-control"
                              placeholder="Planteamiento de la Idea de Negocio.." readonly></textarea>
                </div>
                <span class="help-block" id="helpErrorDescripcionView"></span>
            </div>
        </fieldset>
        <fieldset>
            <legend><i class="fa fa-angle-right"></i> &nbsp;</legend>
            <div class="form-group div-control-excepciones" id="divObservacionView">
                <label class="col-md-3 control-label" for="txtObservacionView"
                       id="lblObservacionView">Observaciones:</label>

                <div class="col-md-6">
                    <textarea id="txtObservacionView" name="txtObservacionView" class="form-control"
                              placeholder="Observaciones.." readonly></textarea>
                </div>
                <span class="help-block" id="helpErrorObservacionView"></span>
            </div>
        </fieldset>
        <div class="form-group form-actions">
            <div class="col-md-8 col-md-offset-4">
                <button id="btnCancelarIdeaView" class="btn btn-sm btn-warning" type="button">
                    <i class="fa fa-repeat"></i>
                    Cancelar
                </button>
                <button class="btn btn-sm btn-warning" type="button" id="btnVolverAlListadoPrincipalDesdeView">
                    <i class="fa fa-reply"></i>
                    Volver al Listado Principal
                </button>
            </div>
        </div>
        <input type="hidden" id="hdnIdRelaboralView" value="0">
        <input type="hidden" id="hdnIdIdeaView" value="0">
    </div>
</div>
</div>
<!--</form></div>-->
</body>
</div>


<div id="divMsjeNotificacionError">
    <div id="divMsjePorError">
    </div>
</div>
<div id="divMsjeNotificacionWarning">
    <div id="divMsjePorWarning">
    </div>
</div>
<div id="divMsjeNotificacionSuccess">
    <div id="divMsjePorSuccess">
    </div>
</div>