
<div class="content-header">
    <div class="header-section">
        <h1>
            <i class="gi gi-dashboard"></i>Pagina de Inicio<br><small>Bienvenido: <?php echo $usuario->nombre; ?></small>
        </h1>
    </div>
</div>
<div class="row">
    <div class="col-sm-6 col-lg-3">
        <div class="widget">
            <div class="widget-simple">
                <a href="/correspondencia" class="widget-icon pull-left themed-background animation-fadeIn">
                    <i class="fa fa-users"></i>
                </a>
                <h3 class="widget-content text-right animation-pullDown">
                    Personal : <strong><?php echo '150'; ?></strong><br />
                    <small>Personal Mi Teleferico</small>
                </h3>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-3">
        <div class="widget">
            <div class="widget-simple">
                <a href="/correspondencia/pendientes" class="widget-icon pull-left themed-background-fire  animation-fadeIn">
                    <i class="gi gi-stopwatch"></i>
                </a>
                <h3 class="widget-content text-right animation-pullDown">
                    Contratos pendientes : <strong><?php echo '200'; ?></strong><br />
                    <small>Personal sin contrato</small>
                </h3>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-3">
        <div class="widget">
            <div class="widget-simple">
                <a href="./page_ready_inbox.php.html" class="widget-icon pull-left themed-background-spring animation-fadeIn">
                    <i class="fa fa-file-text"></i>
                </a>
                <h3 class="widget-content text-right animation-pullDown">
                    Contratos concluidos : <strong><?php echo 7 ?></strong>
                    <small>Personal retirado</small>
                </h3>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-3">
        <div class="widget">
            <div class="widget-simple">
                <a href="/documentos/listar" class="widget-icon pull-left themed-background-amethyst animation-fadeIn">
                    <i class="fa fa-paperclip"></i>
                </a>
                <h3 class="widget-content text-right animation-pullDown">
                    Archivo <strong><?php echo $nDocs ?></strong>
                    <small>Archivo </small>
                </h3>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 animation-stretchRight">
        <div class="widget">
             <div id="chartdiv" style="width: 100%; height: 400px;">Contenido</div>
        </div>
    </div>
</div>