
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("estado/new", "Create estado")) ?>
</div>

<?php echo $this->tag->form(array("estado/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search estado</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="estado">Estado</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("estado", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
