<script type="text/javascript">
$(document).ready(function () {
		var source =
		{
			datatype: "json",
			datafields: [
				{ name: 'id'},
				{ name: 'p_nombre'},
                                { name: 's_nombre'},
                                { name: 'p_apellido'},
                                { name: 's_apellido'},
                                { name: 'ci', type: 'string'},
                                { name: 'fecha_nac', format: 'date'},
				{ name: 'numero_res'},
				{ name: 'fecha_emi'},
				{ name: 'fecha_apr', format: 'date'}
			],
			url: '../../personal/list',
			cache: false
		};
		var dataAdapter = new $.jqx.dataAdapter(source);
		cargar();
		function cargar(){
                    $("#jqxgrid").jqxGrid(
		{
		width: 950,
		source: dataAdapter,
		sortable: true,
		altRows: true,
		pageable: true,
		pagerMode: 'advanced',
		showfilterrow: true,
		filterable: true,
		columns: [
                    { text: 'Nro', datafield: 'id',filtertype: 'input', width: 50},
                    { text: '1o Nombre', datafield: 'p_nombre', filtertype: 'input',width: 100 },
                    { text: '2o Nombre', datafield: 's_nombre', filtertype: 'input',width: 100 },
                    { text: '1o Apellido', datafield: 'p_apellido', filtertype: 'input',width: 100 },
                    { text: '2o Apellido', datafield: 's_apellido', filtertype: 'input',width: 100 },
                    { text: 'Doc. Ident.', datafield: 'ci', type: 'string',filtertype: 'input',width: 100 },
                    { text: 'Fecha Nac.', datafield: 'fecha_nac', format: 'date', filtertype: 'range', cellsformat: 'yyyy', width: 100},
                    { text: 'Editar', datafield: 'Editar', width: 100,sortable: false, filterable: false, columntype: 'button', cellsrenderer: function () {
                        return "Editar";
                    }, buttonclick: function (row) {
                        editrow = row;
                        var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
                        //window.open("/archivo/gestion/", "_blank");
                        document.location.href = '/personal/editar/'+dataRecord.id;
                        /*// open the popup window when the user clicks a button.
                        editrow = row;
                        var offset = $("#jqxgrid").offset();
                        $("#popupWindow").jqxWindow({ position: { x: parseInt(offset.left) + 60, y: parseInt(offset.top) + 60 } });
                        // get the clicked row's data and initialize the input fields.
                        var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
                        $("#titulo").text("Editar");
                        $("#id").val(dataRecord.id);
                        $("#tipo_resolucion").val(dataRecord.tipo_resolucion);
                        $("#numero_res").val(dataRecord.numero_res);
                        var fecha=dataRecord.fecha_emi;
                        fecha=fecha.replace("-", "/").replace("-", "/");	  
                        fecha= new Date(fecha);
                        fecha.setDate(fecha.getDate());
                        $("#fecha_emi").jqxDateTimeInput('setDate', fecha);
                        var fecha=dataRecord.fecha_apr;
                        fecha=fecha.replace("-", "/").replace("-", "/");	  
                        fecha= new Date(fecha);
                        fecha.setDate(fecha.getDate());
                        $("#fecha_apr").jqxDateTimeInput('setDate', fecha);
                        // show the popup window.
                        $("#popupWindow").jqxWindow('open');*/
                    }
                    },
                    { text: 'Eliminar', datafield: 'Eliminar',width:100, sortable:false, filterable: false, columntype: 'button', cellsrenderer: function () {
                        return "Eliminar";
                    }, buttonclick: function (row) {
                        editrow = row;
                        var offset = $("#jqxgrid").offset();
                        $("#popupWindow_delete").jqxWindow({ position: { x: parseInt(offset.left) + 60, y: parseInt(offset.top) + 60 } });
                        var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
                        $("#id").val(dataRecord.id);
                        $("#popupWindow_delete").jqxWindow('open');
                    }
                    },
                    { text: 'Ver', datafield: 'Ver',width:100, sortable:false, filterable: false, columntype: 'button', cellsrenderer: function () {
                        return "Ver";
                    }, buttonclick: function (row) {
                        editrow = row;
                        var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
                        document.location.href = '/personal/visualizar/'+dataRecord.id;
                    }
                    }
		]
                });
                }
		// initialize the popup window and buttons.
            $("#popupWindow").jqxWindow({
                width: 850,height:500, resizable: false,  isModal: true, autoOpen: false, cancelButton: $("#Cancel"), modalOpacity: 0.01           
            });
            $("#popupWindow_delete").jqxWindow({
                width: 400, resizable: false,  isModal: true, autoOpen: false, cancelButton: $("#Cancel"), modalOpacity: 0.01           
            });
            // update the edited row when the user clicks the 'Save' button.
            $("#add").click(function(){
                //$("#page-content").load('../../personal/registro');
                document.location.href = '../../personal/registro';
            	/*$("#titulo").text("Adicionar");
            	$("#id").val("");
            	$("#tipo_resolucion").val("");
            	$("#numero_res").val("");
            	$("#popupWindow").jqxWindow('open');
            	$("#fecha_emi").jqxDateTimeInput({width: '250px', height: '25px',formatString:'yyyy-MM-dd'});
            	fecha= new Date();
  				fecha.setDate(fecha.getDate());
				$("#fecha_emi").jqxDateTimeInput('setDate', fecha);
				fecha= new Date();
  				fecha.setDate(fecha.getDate());
				$("#fecha_apr").jqxDateTimeInput('setDate', fecha);*/
            });

            $("#Save").click(function () {
            	var fecha_apr = $('#fecha_apr').jqxDateTimeInput('getDate');
            	var fecha_emi = $('#fecha_emi').jqxDateTimeInput('getDate');
            	var v=$.ajax({
                    	url:'../../resoluciones/save/',
                    	type:'POST',
                    	datatype: 'json',
			data:{id:$("#id").val(),tipo_resolucion:$("#tipo_resolucion").val(),numero_res:$("#numero_res").val(),fecha_apr:fecha_apr,fecha_emi:fecha_emi},
			success: function(data) { cargar(); //alert(data); 
			}, //mostramos el error
			error: function() { alert('Se ha producido un error Inesperado'); }
		});
                $("#popupWindow").jqxWindow('hide');
               // }
            });

            $("#Eliminar").click(function () {
            	if (editrow >= 0) {
                    var v=$.ajax({
                    	url:'../../personal/delete/',
                    	type:'POST',
                    	datatype: 'json',
						data:{id:$("#id").val()},
						success: function(data) { cargar(); //alert('Guardado Correctamente'); 
												}, //mostramos el error
						error: function() { alert('Se ha producido un error Inesperado'); }
					});
					//$('#jqxgrid').jqxGrid();
                    $("#popupWindow_delete").jqxWindow('hide');
                }
            });

            // create a jqxDateTimeInput.
            //var f='2014-01-01'; 
               	$("#fecha_emi").jqxDateTimeInput({width: '250px', height: '25px',formatString:'yyyy-MM-dd'});
                $("#fecha_apr").jqxDateTimeInput({width: '250px', height: '25px',formatString:'yyyy-MM-dd'});
	});
</script>

<div class="row">
	<div class="col-lg-12">
            <h1><b>Lista de Personal</b></h1>		
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<?php //echo $this->flashSession->output() ?>
				<div style="margin-left: 5px;">
					<div>
						<input id="add" type="button" value=" (+) Adicionar" />
					</div>
				</div>
				<br>
				<div class="table-responsive">
					<div id="jqxgrid"></div>
				</div>

				<div style="margin-top: 30px;">
            		<div id="cellbegineditevent"></div>
            		<div style="margin-top: 10px;" id="cellendeditevent"></div>
       			</div>
				<div id="popupWindow">
					<div id="titulo">Editar</div>
					<div style="overflow: hidden;">
						<table>
							<tr>
								<td align="right">id:</td>
								<td align="left"><input id="id" name="id" type="hidden" /></td>
							</tr>
							<tr>
								<td align="right">Tipo Resolución:</td>
								<td align="left"><input id="tipo_resolucion" name="tipo_resolucion" type="text" /></td>
							</tr>
							<tr>
								<td align="right">Numero Resolución:</td>
								<td align="left"><input id="numero_res" name="numero_res" type="text" /></td>
							</tr>
							<tr>
								<td align="right">Fecha Emisión:</td>
								<td align="left"><div id='fecha_emi'></div></td>
							</tr>
							<tr>
								<td align="right">Fecha Aprobación:</td>
								<td align="left"><div id='fecha_apr'></div></td>
							</tr>
							<tr>
								<td align="right"></td>
								<td style="padding-top: 10px;" align="right">
								<input style="margin-right: 5px;" type="button" id="Save" value="Save" />
								<input id="Cancel" type="button" value="Cancel" />
								</td>
							</tr>
						</table>
					</div>
				</div>

				<div id="popupWindow_delete">
					<div>Eliminar</div>
					<div style="overflow: hidden;">
						<table>
							<tr>
								<td align="left">Esta seguro de Eliminar el registro</td>
							</tr>
							<tr>
								<td align="right"></td>
								<td style="padding-top: 10px;" align="right">
								<input style="margin-right: 5px;" type="button" id="Eliminar" value="Eliminar" />
								<input id="Cancel" type="button" value="Cancel" />
								</td>
							</tr>
						</table>
					</div>
				</div>

			</div>
		</div>
		
	</div>
</div>

