<h1>Adicionar Fuente de Financiamiento</h1>
<form method="post" action="">
	<div>
		<label>Codigo:</label>
		<input type="text" name="codigo" value="">	
	</div>
	<div>
		<label>Fuente:</label>
		<input type="text" name="fuente" value="">	
	</div>
	<div>
		<label>Descripción</label>
		<input type="text" name="descripcion" value="">	
	</div>
	<div>
		<button>Guardar</button>
		<a href="../">Cancelar</a>
	</div>
</form>