<h1>Procesos</h1>
<p><a href="/fuentefinanciamientos/add/">Adicionar</a></p>
<p><?php echo $this->flashSession->output() ?></p>
<div class="table-responsive">
	<table id="general-table" class="table table-striped table-vcenter">
	<thead>
		<tr>
			<th>Nro</th>
			<th>Codigo</th>
			<th>Fuente</th>
			<th>Descripción</th>
			<th>Acción</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($fuente as $p) { ?>
		<tr>
			<td><?php echo $p->id ?></td>
			<td><?php echo $p->codigo ?></td>
			<td><?php echo $p->fuente ?></td>
			<td><?php echo $p->descripcion ?></td>
			<td><a href="../fuentefinanciamientos/edit/<?php echo $p->id ?>">Editar</a> <a href="../fuentefinanciamientos/delete/<?php echo $p->id ?>">Eliminar</a></td>
		</tr>
		<?php } ?>
	</tbody>
		
	</table>
	
</div>