<?php

 use Phalcon\Tag; ?>


<div class="profile left">
    
    <form>
        <div class="clearfix">
            
            <label for="name">Responsable:</label>
            <div class="input">
                <?php
                echo Tag::select(array('responsable',
                    Users::find("id_oficina='$user->id_oficina'"),
                    "using" => array('id' => "nombre")));
                ?>                
            </div>
        </div>

        <div class="clearfix">
            <input type="button" value="Update" class="btn btn-primary btn-large btn-info" onclick="Profile.validate()">
            &nbsp;

        </div>
    </form>
</div>

<?php echo $this->tag->form("etapa/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("etapa", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create etapa</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="etapa">Etapa</label>
        </td>
        <td align="left">
<?php echo $this->tag->textField(array("etapa", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
