<h1>Componentes</h1>
<p><a href="/componentes/add/">Adicionar</a></p>
<p><?php echo $this->flashSession->output() ?></p>
<div class="table-responsive">
	<table id="general-table" class="table table-striped table-vcenter">
	<thead>
		<tr>
			<th>Nro</th>
			<th>Normativa</th>
			<th>Componente</th>
			<th>Descripción</th>
			<th>Acción</th>
		</tr>	
	</tbody>
	<tbody>
		<?php foreach ($componente as $p) { ?>
		<tr>
			<td><?php echo $p->id ?></td>
			<td><?php echo $p->normativa ?></td>
			<td><?php echo $p->componente ?></td>
			<td><?php echo $p->descripcion ?></td>
			<td><a href="../componentes/edit/<?php echo $p->id ?>">Editar</a> <a href="../componentes/delete/<?php echo $p->id ?>">Eliminar</a></td>
		</tr>
		<?php } ?>
	</thead>
</table>
</div>