<div class="row">
	<div class="col-lg-12">
		<h1>Adicionar Unidad Administrativa</h1>		
	</div>
</div>
<div class="row">
	<div class="col-lg-6">
		<form method="post" action="" class="form-horizontal">
		<input type="hidden" name="resolucion_ministerial_id" value="<?php echo $resolucion_ministerial_id ?>">
			<div class="form-group">
				<label class="col-lg-3 control-label">Depende de</label>
				<div class="col-lg-9">
					<?php echo $padre; ?>
				</div>
			</div>
			<div class="form-group">
				<label class="col-lg-3 control-label">Nivel Estructural</label>
				<div class="col-lg-9">
					<?php echo $nivelestructural; ?>
				</div>
			</div>
			<div class="form-group">
				<label class="col-lg-3 control-label">Unidad Administrativa</label>
				<div class="col-lg-9">
					<input type="text" name="unidad_administrativa" class="form-control" placeholder="ingrese unidad administrativa" required>
				</div>
			</div>
			<div class="form-group">
				<label class="col-lg-3 control-label">Sigla</label>
				<div class="col-lg-9">
					<input type="text" name="sigla" id="sigla" class="form-control" placeholder="ingrese sigla" value="<?php echo $sigla ?>" required>
				</div>
			</div>
			<div class="form-group">
				<label class="col-lg-3 control-label">Codigo</label>
				<div class="col-lg-9">
					<input type="text" name="codigo" id="codigo" class="form-control" placeholder="Codigo Unidad" value="<?php echo $codigo ?>" required>
				</div>
			</div>
			<div class="form-group">
				<label class="col-lg-3 control-label">Area</label>
				<div class="col-lg-9">
					<input type="radio" name="area_sustantiva" value="1" checked="checked"/> Sustantiva o Misional
					<input type="radio" name="area_sustantiva" value="0"/> No Sustantiva
				</div>
			</div>
			<div class="form-group">
				<label class="col-lg-3 control-label">Es Unidad Asistente del Dependiente?</label>
				<div class="col-lg-9">
					<input type="radio" name="asistente" value="1"  /> Si
					<input type="radio" name="asistente" value="0" checked="checked"/> No
				</div>
			</div>
			<div class="form-group">
				<label class="col-lg-3 control-label">Color</label>
				<div class="col-lg-9">
					<input type="text" name="color" id="color" class="kolorPicker form-control" placeholder="Color de la unidad" value="#11203A" required>
				</div>
			</div>
			<div class="form-group">
				<label class="col-lg-3 control-label">Fecha Inicio</label>
				<div class="col-lg-9">
					<input type="text" id="fecha_ini" name="fecha_ini" value="<?php echo date("d-m-Y") ?>" class="form-control input-datepicker-close" data-date-format="dd-mm-yyyy" placeholder="dd-mm-yyyy" />
				</div>
			</div>
			
			<div class="form-group">
				<div class="col-lg-12" align="center">
					<button type="submit" class="btn btn-primary">Guardar</button>
					<a href="../" class="btn btn-primary">Cancelar</a>
				</div>
			</div>

		</div>
	</form>

</div>
</div>

<script type="text/javascript">
	$(document).ready(function () {
		$('#padre_id').change(function(){
    var id=$(this).val(); //id oficina
    var v=$.ajax({
    	url:'/ajax/sigla/'+id,
    	type:'POST',
    	datatype: 'json',
	success: function(data) { $("#sigla").val(data);}, //mostramos el error
	error: function() { alert('Se ha producido un error Inesperado'); }
});
});

		var color = $("#color").val();
		$("#color").css({'background-color' : color,'color' : color});

		$("#color").change(function(){
			var color = $("#color").val();
			$("#color").css({'background-color' : color,'color' : color});
		});
		
		
	});
</script>