<style>
    #divCalendarioSmall div {
        margin: 0 auto;
    }
</style>
<h3><i class="gi gi-alarm "></i> Mis Horarios y Marcaciones</h3>
<input type="hidden" id="hdnIdRelaboralUsuario" name="hdnIdRelaboralUsuario" value="<?php echo $idRelaboral; ?>">
<input type="hidden" id="hdnCiUsuario" name="hdnciUsuario" value="<?php echo $ci; ?>">
<div class="row">
    <div class="col-md-12" id="divCalendarioHorarios">
        <div class="block block-alt-noborder full">
            <div class="block-title">
                <div class="block-options pull-right">
                    <a id="btnRefrescarCalendarioLaboralAndExcept" class="btn btn-alt btn-sm btn-default"
                       title="Refrescar Todo" data-toggle="tooltip" href="javascript:void(0)"
                       data-original-title="Refrescar">
                        <i class="fa fa-refresh"></i>
                    </a>
                    <a id="btnImprimirCalendarioHorarios" class="btn btn-alt btn-sm btn-default"
                       title="Imprimir Calendario" data-toggle="tooltip" href="javascript:void(0)"
                       data-original-title="Imprimir">
                        <i class="fa fa-print"></i>
                    </a>
                </div>
                <h2><strong>Calendario</strong> de Horarios & Marcaciones</h2>
            </div>
            <div id="calendar" class="calendar_h"></div>
        </div>
    </div>
    <div class="col-md-12" id="divCalendarioDetalles">
        <div class="block block-alt-noborder full">
            <div class="block-title">
                <div class="block-options pull-right">
                    <a id="btnRefrescarCalendarioDetalle" class="btn btn-alt btn-sm btn-default"
                       title="Refrescar Calendario Detalle" data-toggle="tooltip" href="javascript:void(0)"
                       data-original-title="Refrescar">
                        <i class="fa fa-refresh"></i>
                    </a>
                    <a id="btnImprimirCalendarioDetalle" class="btn btn-alt btn-sm btn-default"
                       title="Imprimir Calendario" data-toggle="tooltip" href="javascript:void(0)"
                       data-original-title="Imprimir">
                        <i class="fa fa-print"></i>
                    </a>
                </div>
                <h2><strong>Calendario</strong> Detalle</h2>
            </div>
            <div>
                <div id="divGridCalendario"></div>
            </div>
        </div>
    </div>
    <div class="col-md-12" id="divReporteHorariosMarcaciones">
        <!--<div class="block block-alt-noborder full">
            <div class="block-title">
                <div class="block-options pull-right">
                    <a id="btnImprimirReporte" class="btn btn-alt btn-sm btn-default"
                       title="Imprimir Reporte" data-toggle="tooltip" href="javascript:void(0)"
                       data-original-title="Imprimir Reporte">
                        <i class="fa fa-print"></i>
                    </a>
                </div>
                <h2><strong>Reporte</strong> Horarios Vs. Marcaciones</h2>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label" for="txtFechaIniRango">Rango:</label>
                <div class="col-md-8">
                    <div class="input-group input-daterange" data-date-format="dd/mm/yyyy">
                        <input type="text" id="txtFechaIniRango" name="txtFechaIniRango"
                               class="form-control text-center input-datepicker-close" data-date-format="dd-mm-yyyy" placeholder="Desde">
                        <span class="input-group-addon"><i class="fa fa-angle-right"></i></span>
                        <input type="text" id="txtFechaFinRango" name="txtFechaFinRango"
                               class="form-control text-center  input-datepicker-close" data-date-format="dd-mm-yyyy" placeholder="Hasta">
                    </div>
                </div>
                <div class="col-md-2">
                    <button class="btn btn-sm btn-success" type="button" id="btnGenerarReporte">
                        <i class="fa fa-search"></i>
                        Buscar
                    </button>
                </div>
            </div>
            <div id="divGrillaReporte" class="div-reporte"></div>
            <h6><b>NOTA: </b>La planilla salarial se calcula entre el 21 del mes anterior al 20 del mes de la planilla.</h6>
        </div>-->
        <div class="block block-alt-noborder full">
            <div style="text-align: center;">
                <div class="block full" id="divCalendarioSmall"></div>
            </div>
        </div>
    </div>
</div>
<div style="display: none;" class="modal fade bs-example-modal-lg" id="popupDescripcionHorario" tabindex="-1"
     role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <form class="form-horizontal" id="testForm_perfil" data-toggle="validator" onsubmit="return false;"/>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Cerrar</span></button>
                <h4 class="modal-title" id="tituloModal">Horario</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                DATOS DEL HORARIO SELECCIONADO
                            </div>
                            <div class="panel-body form-horizontal">
                                <div class="form-group">
                                    <label class="col-sm-3 control-label" for="txtNombreHorario">Nombre Horario:</label>

                                    <div class="col-md-6" form-group>
                                        <input type="text" id="txtNombreHorario" class="form-control" readonly>
                                    </div>
                                </div>
                                <div class="form-group" id="divNombreAlternativoHorario">
                                    <label class="col-sm-3 control-label" for="txtNombreAlternativoHorario">Nombre
                                        Alternativo:</label>

                                    <div class="col-md-6" form-group>
                                        <textarea id="txtNombreAlternativoHorario" class="form-control"
                                                  readonly></textarea>
                                    </div>
                                </div>
                                <div class="form-group" id="divColorHorario">
                                    <label class="col-sm-3 control-label" for="txtColorHorario">Color:</label>

                                    <div class="col-md-6" form-group>
                                        <input type="text" id="txtColorHorario" value="#FFFFFF" class="form-control"
                                               readonly>
                                    </div>
                                </div>
                                <fieldset>
                                    <legend><i class="fa fa-angle-right"></i> Horario Entrada / Salida</legend>
                                    <div class="form-group">
                                        <div class="div-calendario-laboral" id="divHoraEntHorario">
                                            <label class="col-sm-2 control-label"
                                                   for="txtHoraEntHorario">Entrada:</label>

                                            <div class="col-md-2" form-group>
                                                <input id="txtHoraEntHorario" name="txtHoraEntHorario"
                                                       placeholder="Hora de entrada." class="form-control" type="text"
                                                       readonly>
                                            </div>
                                        </div>
                                        <div class="div-calendario-laboral" id="divHoraSalHorario">
                                            <label class="col-sm-2 control-label"
                                                   for="txtHoraSalHorario">Salida:</label>

                                            <div class="col-md-2" form-group>
                                                <input id="txtHoraSalHorario" name="txtHoraSalHorario"
                                                       class="form-control" type="text" readonly>
                                            </div>
                                        </div>
                                        <label class="col-sm-2 control-label" for="txtHorasLaborales">Horas
                                            Laborales:</label>

                                        <div class="col-md-2">
                                            <input id="txtHorasLaborales" name="txtHorasLaborales"
                                                   placeholder="Horas Laborales." type="text" class="form-control"
                                                   readonly>
                                        </div>
                                    </div>
                                </fieldset>
                                <fieldset>
                                    <legend><i class="fa fa-angle-right"></i> Rango Control Marcaciones</legend>
                                    <div class="form-group">
                                        <div class="div-calendario-laboral" id="divHoraInicioRangoEnt">
                                            <label class="col-sm-3 control-label" for="txtHoraInicioRangoEnt">Inicio
                                                Entrada:</label>

                                            <div class="col-md-3">
                                                <input id="txtHoraInicioRangoEnt" name="txtHoraInicioRangoEnt"
                                                       placeholder="Hora de entrada." class="form-control" type="text"
                                                       readonly>
                                            </div>
                                        </div>
                                        <div class="div-calendario-laboral" id="divHoraFinalizacionRangoEnt">
                                            <label class="col-sm-3 control-label" for="txtHoraFinalizacionRangoEnt">Finalizaci&oacute;n
                                                Entrada:</label>

                                            <div class="col-md-3">
                                                <input id="txtHoraFinalizacionRangoEnt"
                                                       name="txtHoraFinalizacionRangoEnt" class="form-control"
                                                       type="text" readonly>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="div-calendario-laboral" id="divHoraInicioRangoSal">
                                            <label class="col-sm-3 control-label" for="txtHoraInicioRangoSal">Inicio
                                                Salida:</label>

                                            <div class="col-md-3">
                                                <input id="txtHoraInicioRangoSal" name="txtHoraInicioRangoSal"
                                                       placeholder="Hora de inicio de salida." class="form-control"
                                                       type="text" readonly>
                                            </div>

                                        </div>
                                        <div class="div-calendario-laboral" id="divHoraFinalizacionRangoSal">
                                            <label class="col-sm-3 control-label" for="txtHoraFinalizacionRangoSal">Fin
                                                Salida:</label>

                                            <div class="col-md-3">
                                                <input id="txtHoraFinalizacionRangoSal"
                                                       name="txtHoraFinalizacionRangoSal"
                                                       placeholder="Hora de finalizaci&oacute;n de salida."
                                                       class="form-control" type="text" readonly>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="div-calendario-laboral" id="divPermitirCruce">
                                            <label class="col-sm-3 control-label" for="txtPermitirCruce">¿Permitir
                                                Cruce?:</label>
                                            <div class="col-md-3">
                                                <input type="checkbox" id="chkPermitirCruce" onclick="return false;">
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                                <fieldset>
                                    <legend><i class="fa fa-angle-right"></i> Rango Fechas</legend>
                                    <div class="form-group">
                                        <div class="div-calendario-laboral" id="divHorarioFechaIni">
                                            <label class="col-sm-3 control-label" for="txtHorarioFechaIni">Fecha
                                                Inicio:</label>

                                            <div class="col-md-3">
                                                <input id="txtHorarioFechaIni" name="txtHorarioFechaIni"
                                                       class="form-control input-datepicker" placeholder="Desde"
                                                       data-date-format="dd-mm-yyyy" type="text">
                                            </div>
                                        </div>
                                        <div class="div-calendario-laboral" id="divHorarioFechaFin">
                                            <label class="col-sm-3 control-label" for="txtHorarioFechaFin">Fecha
                                                Fin:</label>

                                            <div class="col-md-3">
                                                <input id="txtHorarioFechaFin" name="txtHorarioFechaFin"
                                                       class="form-control input-datepicker" placeholder="Hasta"
                                                       data-date-format="dd-mm-yyyy" type="text">
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                                <fieldset>
                                    <legend><i class="fa fa-angle-right"></i> Observaciones</legend>
                                    <div class="form-group div-move-relab" id="divObservacion">
                                        <label class="col-md-3 control-label"
                                               for="txtObservacion">Observaciones:</label>

                                        <div class="col-md-6">
                                            <textarea id="txtObservacion" name="txtObservacion" class="form-control"
                                                      placeholder="Observaciones.." readonly></textarea>
                                        </div>
                                    </div>
                                </fieldset>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" id="btnCerrarHorario" class="btn btn-primary" data-dismiss="modal"><i
                        class="fa fa-compress"></i>Cerrar
                </button>
            </div>
            </form>
        </div>
    </div>
</div>
<div id="divMsjeNotificacionError">
    <div id="divMsjePorError">
    </div>
</div>
<div id="divMsjeNotificacionWarning">
    <div id="divMsjePorWarning">
    </div>
</div>