<div class="table-responsive">
    <table id="general-table" class="table table-striped table-vcenter">
        <thead>
            <tr>
                <th style="width: 80px;" class="text-center"><input type="checkbox" /></th>
                <th style="width: 150px;" class="text-center"><i class="gi gi-user"></i></th>
                <th>Cliente</th>
                <th>Email</th>
                <th>Subscription</th>
                <th style="width: 150px;" class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-center"><input type="checkbox" id="checkbox1-1" name="checkbox1-1" /></td>
                <td class="text-center"><img src="./img/placeholders/avatars/avatar3.jpg" alt="avatar" class="img-circle" /></td>
                <td><a href="./page_ready_user_profile.php.html">client1</a></td>
                <td>client1@example.com</td>
                <td><a href="javascript:void(0)" class="label label-warning">Trial</a></td>
                <td class="text-center">
                    <div class="btn-group btn-group-xs">
                        <a href="javascript:void(0)" data-toggle="tooltip" title="Edit" class="btn btn-default"><i class="fa fa-pencil"></i></a>
                        <a href="javascript:void(0)" data-toggle="tooltip" title="Delete" class="btn btn-danger"><i class="fa fa-times"></i></a>
                    </div>
                </td>
            </tr>
            <tr>
                <td class="text-center"><input type="checkbox" id="checkbox1-2" name="checkbox1-2" /></td>
                <td class="text-center"><img src="./img/placeholders/avatars/avatar7.jpg" alt="avatar" class="img-circle" /></td>
                <td><a href="./page_ready_user_profile.php.html">client2</a></td>
                <td>client2@example.com</td>
                <td><a href="javascript:void(0)" class="label label-success">VIP</a></td>
                <td class="text-center">
                    <div class="btn-group btn-group-xs">
                        <a href="javascript:void(0)" data-toggle="tooltip" title="Edit" class="btn btn-default"><i class="fa fa-pencil"></i></a>
                        <a href="javascript:void(0)" data-toggle="tooltip" title="Delete" class="btn btn-danger"><i class="fa fa-times"></i></a>
                    </div>
                </td>
            </tr>
            <tr>
                <td class="text-center"><input type="checkbox" id="checkbox1-3" name="checkbox1-3" /></td>
                <td class="text-center"><img src="./img/placeholders/avatars/avatar11.jpg" alt="avatar" class="img-circle" /></td>
                <td><a href="./page_ready_user_profile.php.html">client3</a></td>
                <td>client3@example.com</td>
                <td><a href="javascript:void(0)" class="label label-info">Business</a></td>
                <td class="text-center">
                    <div class="btn-group btn-group-xs">
                        <a href="javascript:void(0)" data-toggle="tooltip" title="Edit" class="btn btn-default"><i class="fa fa-pencil"></i></a>
                        <a href="javascript:void(0)" data-toggle="tooltip" title="Delete" class="btn btn-danger"><i class="fa fa-times"></i></a>
                    </div>
                </td>
            </tr>
            <tr>
                <td class="text-center"><input type="checkbox" id="checkbox1-4" name="checkbox1-4" /></td>
                <td class="text-center"><img src="./img/placeholders/avatars/avatar14.jpg" alt="avatar" class="img-circle" /></td>
                <td><a href="./page_ready_user_profile.php.html">client4</a></td>
                <td>client4@example.com</td>
                <td><a href="javascript:void(0)" class="label label-success">VIP</a></td>
                <td class="text-center">
                    <div class="btn-group btn-group-xs">
                        <a href="javascript:void(0)" data-toggle="tooltip" title="Edit" class="btn btn-default"><i class="fa fa-pencil"></i></a>
                        <a href="javascript:void(0)" data-toggle="tooltip" title="Delete" class="btn btn-danger"><i class="fa fa-times"></i></a>
                    </div>
                </td>
            </tr>
            <tr>
                <td class="text-center"><input type="checkbox" id="checkbox1-5" name="checkbox1-5" /></td>
                <td class="text-center"><img src="./img/placeholders/avatars/avatar10.jpg" alt="avatar" class="img-circle" /></td>
                <td><a href="./page_ready_user_profile.php.html">client5</a></td>
                <td>client5@example.com</td>
                <td><a href="javascript:void(0)" class="label label-primary">Personal</a></td>
                <td class="text-center">
                    <div class="btn-group btn-group-xs">
                        <a href="javascript:void(0)" data-toggle="tooltip" title="Edit" class="btn btn-default"><i class="fa fa-pencil"></i></a>
                        <a href="javascript:void(0)" data-toggle="tooltip" title="Delete" class="btn btn-danger"><i class="fa fa-times"></i></a>
                    </div>
                </td>
            </tr>
            <tr>
                <td class="text-center"><input type="checkbox" id="checkbox1-6" name="checkbox1-6" /></td>
                <td class="text-center"><img src="./img/placeholders/avatars/avatar10.jpg" alt="avatar" class="img-circle" /></td>
                <td><a href="./page_ready_user_profile.php.html">client6</a></td>
                <td>client6@example.com</td>
                <td><a href="javascript:void(0)" class="label label-info">Business</a></td>
                <td class="text-center">
                    <div class="btn-group btn-group-xs">
                        <a href="javascript:void(0)" data-toggle="tooltip" title="Edit" class="btn btn-default"><i class="fa fa-pencil"></i></a>
                        <a href="javascript:void(0)" data-toggle="tooltip" title="Delete" class="btn btn-danger"><i class="fa fa-times"></i></a>
                    </div>
                </td>
            </tr>
            <tr>
                <td class="text-center"><input type="checkbox" id="checkbox1-7" name="checkbox1-7" /></td>
                <td class="text-center"><img src="./img/placeholders/avatars/avatar11.jpg" alt="avatar" class="img-circle" /></td>
                <td><a href="./page_ready_user_profile.php.html">client7</a></td>
                <td>client7@example.com</td>
                <td><a href="javascript:void(0)" class="label label-primary">Personal</a></td>
                <td class="text-center">
                    <div class="btn-group btn-group-xs">
                        <a href="javascript:void(0)" data-toggle="tooltip" title="Edit" class="btn btn-default"><i class="fa fa-pencil"></i></a>
                        <a href="javascript:void(0)" data-toggle="tooltip" title="Delete" class="btn btn-danger"><i class="fa fa-times"></i></a>
                    </div>
                </td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="6">
                    <div class="btn-group btn-group-sm pull-right">
                        <a href="javascript:void(0)" class="btn btn-primary" data-toggle="tooltip" title="Settings"><i class="fa fa-cog"></i></a>
                        <div class="btn-group btn-group-sm dropup">
                            <a href="javascript:void(0)" class="btn btn-primary pull-right dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
                            <ul class="dropdown-menu dropdown-custom dropdown-menu-right">
                                <li><a href="javascript:void(0)"><i class="fa fa-print pull-right"></i> Print</a></li>
                                <li class="dropdown-header"><i class="fa fa-share pull-right"></i> Export As</li>
                                <li>
                                    <a href="javascript:void(0)">.pdf</a>
                                    <a href="javascript:void(0)">.cvs</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="btn-group btn-group-sm">
                        <a href="javascript:void(0)" class="btn btn-primary" data-toggle="tooltip" title="Edit Selected"><i class="fa fa-pencil"></i></a>
                        <a href="javascript:void(0)" class="btn btn-primary" data-toggle="tooltip" title="Delete Selected"><i class="fa fa-times"></i></a>
                    </div>
                </td>
            </tr>
        </tfoot>
    </table>
</div>


<?php
foreach ($oficinas as $o) {
    echo $o->oficina;
}?>