<h1>Adicionar Nivel Salarial</h1>
<form method="post" action="">
	<div>
		<label>Resolución:</label>
		<?php echo $resolucion ?>
	</div>
	<div>
		<label>Categoria</label>
		<input type="text" name="categoria" value="">	
	</div>
	<div>
		<label>Clase</label>
		<input type="text" name="clase" value="">	
	</div>
	<div>
		<label>Nivel Salarial</label>
		<input type="text" name="nivel" value="">	
	</div>
	<div>
		<label>Denominacion Cargo</label>
		<input type="text" name="denominacion" value="">	
	</div>
	<div>
		<label>Sueldo</label>
		<input type="text" name="sueldo" value="">	
	</div>
	<div>
		<button>Guardar</button>
		<a href="../">Cancelar</a>
	</div>
</form>