
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("users/new", "Create users")) ?>
</div>

<?php echo $this->tag->form(array("users/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search users</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="superior">Superior</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("superior", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="id_oficina">Id Of Oficina</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id_oficina", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="dependencia">Dependencia</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("dependencia", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="username">Username</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("username", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="password">Password</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("password", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="nombre">Nombre</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("nombre", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="last_login">Last Of Login</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("last_login", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="mosca">Mosca</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("mosca", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="cargo">Cargo</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("cargo", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="email">Email</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("email", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="logins">Logins</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("logins", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="fecha_creacion">Fecha Of Creacion</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("fecha_creacion", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="habilitado">Habilitado</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("habilitado", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="nivel">Nivel</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("nivel", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="genero">Genero</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("genero", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="prioridad">Prioridad</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("prioridad", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="id_entidad">Id Of Entidad</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id_entidad", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="super">Super</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("super", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="cedula_identidad">Cedula Of Identidad</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("cedula_identidad", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="expedido">Expedido</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("expedido", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="theme">Theme</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("theme", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="cite_despacho">Cite Of Despacho</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("cite_despacho", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
