<style>
    .activeDay {background-color:#ff0000 !important;}
</style>
<h2 style="padding-top: 0px; width: 100%;"><b>Gesti&oacute;n de Marcaciones</h2>
<div id='divTabControlMarcaciones'>
<ul>
    <li id="liList">Listado</li>
    <li id="liMarc">Marcaciones</li>
    <li id="liCalc">Descarga por Rango</li>
    <li id="liTurnAndExcept">Calendario</li>
</ul>
<br>
<div style="height: 800px" class="row section" id="divList">
    <div class="col-md-10">
        <!-- Input Grid Block -->
        <div class="block">
            <!-- Input Grid Title -->
            <div class="block-title">
                <div id='jqxWidget'>
                    <div class="col-md-1">
                        <br/>
                        <label>Gesti&oacute;n:</label>
                    </div>
                    <div class="col-sm-2" id="divGestionGen">
                        <select id="lstGestion" class="form-control">
                            <option value="">Seleccionar..</option>
                        </select>
                    </div>
                    <button class="btn btn-sm btn-info" type="button" id="btnBuscarPorGestion" accesskey="i">
                        <i class="fa fa-search"></i>
                        Buscar
                    </button>
                    <div id="divGridRelaborales"></div>
                </div>
            </div>
            <!-- END Input Grid Title -->

        </div>
        <!-- END Input Grid Block -->
    </div>
    <div class="col-md-2">
        <!-- Input Grid Block -->
        <div class="block">
            <!-- Input Grid Title -->
            <div class="block-title">
                <h2>Mostrar</h2>
                <br>
                <!--<input type="checkbox" id="chkAllCols"> Todas / Ninguna-->

                <!--<div id="hintWrapper">
                    <div id="hintSection" class="hint">
                    </div>
                </div>-->
            </div>
            <div id="jqxlistbox"></div>


            <!-- END Input Grid Title -->
        </div>
        <!-- END Input Grid Block -->
    </div>
</div>
<div style="display: none" class="section" id="divMarc">
<form class="navbar-form" id="formMarc">
    <div id="tabFichaPersonal">
        <ul style="margin-left: 30px;">
            <li>Datos Personales</li>
            <li>Contacto Personal</li>
            <li>Contacto Institucional</li>
        </ul>
        <div style="height: 190px;" class="form-horizontal col-sm-12">
            <br>
            <div class="widget">
                <div class="widget-simple themed-background-default">
                    <a href="#" id="aFotoPerfil">
                        <img id="imgFotoPerfil" class="img-rounded pull-right img-perfil">
                    </a>
                    <h4 class="widget-content">
                        <div>
                            <dl class="dl-horizontal" STYLE="color: white;font-size: 13px;">
                                <dt id="dtNombres">Nombres y Apellidos:</dt>
                                <dd id="ddNombres"></dd>
                                <dt id="dtTipoDeDocumento"></dt>
                                <dd id="ddNumeroDeDocumento"></dd>
                                <dt id="dtNacionalidad">Nacionalidad:</dt>
                                <dd id="ddNacionalidad"></dd>
                                <dt id="dtLugarDeNacimiento">Lugar de Nacimiento:</dt>
                                <dd id="ddLugarDeNacimiento"></dd>
                                <dt id="dtFechaDeNacimiento">Fecha de Nacimiento:</dt>
                                <dd id="ddFechaDeNacimiento"></dd>
                            </dl>
                        </div>
                    </h4>
                </div>
            </div>
        </div>
        <div style="display: none;" class="form-horizontal col-sm-12">
            <br>

            <div class="widget">
                <div class="widget-simple themed-background-default">
                    <a href="#" id="aFotoPerfilContactoPer"><img id="imgFotoPerfilContactoPer"
                                                                 class="img-rounded pull-right img-perfil"></a>
                    <h4 class="widget-content">
                        <div>
                            <dl class="dl-horizontal" STYLE="color: white;font-size: 13px;">
                                <dt id="dtDireccion">Direcci&oacute;n:</dt>
                                <dd id="ddDireccion"></dd>
                                <dt id="dtTelefonoFijo">Tel&eacute;fono Fijo:</dt>
                                <dd id="ddTelefonoFijo"></dd>
                                <dt id="dtCelularPer">Celular Personal:</dt>
                                <dd id="ddCelularPer"></dd>
                                <dt id="dtEmailPer">E-Mail Personal:</dt>
                                <dd id="ddEmailPer"></dd>
                                <dt id="dtAuxiliar1">&nbsp;</dt>
                                <dd id="ddAuxiliar1">&nbsp;</dd>
                            </dl>
                        </div>
                    </h4>
                </div>
            </div>
        </div>
        <div style="display: none;" class="form-horizontal col-sm-12">
            <br>

            <div class="widget">
                <div class="widget-simple themed-background-default">
                    <a href="#" id="aFotoPerfilContactoInst"><img id="imgFotoPerfilContactoInst"
                                                                  class="img-rounded pull-right img-perfil"></a>
                    <h4 class="widget-content">
                        <div>
                            <dl class="dl-horizontal" STYLE="color: white;font-size: 13px;">
                                <dt id="dtTelefonoInst">Tel&eacute;fono Inst.:</dt>
                                <dd id="ddTelefonoInst"></dd>
                                <dt id="dtCelularInst">Celular Corporativo:</dt>
                                <dd id="ddCelularInst"></dd>
                                <dt id="dtTelefonoFax">Fax:</dt>
                                <dd id="ddTelefonoFax"></dd>
                                <dt id="dtInternoInst">N&uacute;mero Interno:</dt>
                                <dd id="ddInternoInst"></dd>
                                <dt id="dtEmailInst">E-Mail Institucional:</dt>
                                <dd id="ddEmailInst"></dd>
                            </dl>
                        </div>
                    </h4>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="col-md-10">
        <!-- Input Grid Block -->
        <div class="block">
            <!-- Input Grid Title -->
            <div class="block-title">

                <div id='jqxWidget'>
                    <div>
                        <div class="row">
                            <div class="col-md-1">
                            <br>
                            <label for="txtFechaIniControlMarcaciones">Fechas *:</label>
                            </div>
                            <div class="col-md-4"> <!--input-daterange-->
                                <div class="input-group input-daterange" data-date-format="dd-mm-yyyy">
                                    <input id="txtFechaIniControlMarcaciones" name="txtFechaIniControlMarcaciones" class="form-control input-datepicker-close text-center" data-date-format="dd-mm-yyyy" placeholder="Desde" data-date-min="01-01-2015" data-date-max="31-01-2015" type="text">
                                    <span class="input-group-addon"><!--<i class="fa fa-angle-right"></i>-->Al</span>
                                    <input id="txtFechaFinControlMarcaciones" name="txtFechaFinControlMarcaciones" class="form-control input-datepicker-close text-center" data-date-format="dd-mm-yyyy" placeholder="Hasta" data-date-min="01-01-2015" data-date-max="31-01-2015" type="text">
                                </div>
                            </div>
                            <div class="col-md-1">
                                <button class="btn btn-sm btn-info" type="button" id="btnBuscarControlMarcaciones" accesskey="c">
                                    <i class="gi gi-search"></i>
                                    Buscar
                                </button>
                            </div>
                        </div>
                    </div>
                    </br>
                    <div id="divGridControlMarcaciones"></div>
                </div>
            </div>
            <!-- END Input Grid Title -->

        </div>
        <div align="left">
            <button class="btn btn-sm btn-warning" type="button" id="btnVolverDesdeControlMarcaciones">
                <i class="fa fa-reply"></i>
                Volver al Listado
            </button>
        </div>
        <!-- END Input Grid Block -->
    </div>
    <div class="col-md-2">
        <!-- Input Grid Block -->
        <div class="block">
            <!-- Input Grid Title -->
            <div class="block-title">
                <h2>Mostrar</h2>
                <br>
                <!--<input type="checkbox" id="chkAllCols"> Todas / Ninguna-->

                <!--<div id="hintWrapper">
                    <div id="hintSection" class="hint">
                    </div>
                </div>-->
            </div>
            <div id="divListBoxControlMarcaciones"></div>


            <!-- END Input Grid Title -->
        </div>
        <!-- END Input Grid Block -->
    </div>
    <input type="hidden" id="hdnIdRelaboralControlMarcaciones" value="0">
</form>
</div>
<div style="display: none" class="section" id="divDownload">
    <h6>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>NOTA: </b>Debe seleccionar necesariamente las fechas para el rango en el cual se obtendr&aacute; la descarga de datos. El documento de identidad es alternativo.</h6>
    <form class="navbar-form" id="formDownload">
        <div class="col-md-10">
            <!-- Input Grid Block -->
            <div class="block">
                <!-- Input Grid Title -->
                <div class="block-title">

                    <!--<h2>Descarga General de Marcaciones</h2>-->
                    <div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="input-group input-daterange" data-date-format="dd-mm-yyyy">
                                    <input id="txtFechaIniDescarga" name="txtFechaIniDescarga" class="form-control input-datepicker-close text-center" data-date-format="dd-mm-yyyy" placeholder="Desde" data-date-min="01-01-2015" data-date-max="31-01-2015" type="text">
                                    <span class="input-group-addon"><!--<i class="fa fa-angle-right"></i>-->Al</span>
                                    <input id="txtFechaFinDescarga" name="txtFechaFinDescarga" class="form-control input-datepicker-close text-center" data-date-format="dd-mm-yyyy" placeholder="Hasta" data-date-min="01-01-2015" data-date-max="31-01-2015" type="text">
                                </div>
                            </div>
                            &nbsp;
                            <div class="col-md-2">
                                <input id="txtCiDescarga" name="txtCiDescarga" class="form-control" placeholder="Doc. Identidad" type="text">
                            </div>
                            <div class="col-md-1">
                                <button class="btn btn-sm btn-info" type="button" id="btnDescargarMarcaciones" accesskey="c">
                                    <i class="fa fa-chevron-circle-down"></i>
                                    Descargar
                                </button>
                            </div>
                            <div class="col-md-1">
                                <button class="btn btn-sm btn-success" type="button" id="btnBuscarMarcaciones" accesskey="c">
                                    <i class="gi gi-search"></i>
                                    Buscar
                                </button>
                            </div>
                        </div>
                    </div>
                    </br>
                    <div id='jqxWidget'>
                        <div id="divCarga" style="display:none" align="center">
                            <img src="../images/barra_carga.gif" />
                        </div>
                        <div id="divGridDescargaMarcacionesRango"></div>
                    </div>
                </div>
                <!-- END Input Grid Title -->
                <!--<button class="btn btn-sm btn-primary" type="button" id="btnExportarTodasMarcacionesRangoExcel" accesskey="i">
                    <i class="fi fi-xls"></i>
                    Exportar Excel Todo
                </button>-->
                <button class="btn btn-sm btn-primary" type="button" id="btnExportarDescargasExcel" accesskey="i">
                    <i class="fi fi-xls"></i>
                    Exportar Excel
                </button>
                <button class="btn btn-sm btn-primary" type="button" id="btnExportarDescargasPDF" accesskey="i">
                    <i class="fi fi-pdf"></i>
                    Exportar PDF
                </button>
                <button class="btn btn-sm btn-primary" type="button" id="btnDesagrupartododescargas">
                    <i class="fa fa-chain-broken"></i>
                    Desagrupar Todo
                </button>
                <button class="btn btn-sm btn-primary" type="button" id="btnDesfiltrartododescargas">
                    <i class="gi gi-sorting"></i>
                    Desfiltrar Todo
                </button>
                <button class="btn btn-sm btn-warning" type="button" id="btnVolverDesdeDescargas">
                    <i class="fa fa-reply"></i>
                    Volver al Listado
                </button>
            </div>
            <!-- END Input Grid Block -->
        </div>
        <div class="col-md-2">
            <!-- Input Grid Block -->
            <div class="block">
                <!-- Input Grid Title -->
                <div class="block-title">
                    <h2>Mostrar</h2>
                    <br>
                    <!--<input type="checkbox" id="chkAllCols"> Todas / Ninguna-->

                    <!--<div id="hintWrapper">
                        <div id="hintSection" class="hint">
                        </div>
                    </div>-->
                </div>
                <div id="divListBoxDescargasRango"></div>


                <!-- END Input Grid Title -->
            </div>
            <!-- END Input Grid Block -->
        </div>

        <!--<div id="divGridControlMarcaciones"></div>-->

    </form>

</div>
<div style="display: none" class="section" id="divTurnAndMarc">
    <form class="navbar-form" id="form" onsubmit="return false;">
        <div id="tabFichaPersonalTurnAndExcept">
            <ul style="margin-left: 30px;">
                <li>Relaci&oacute;n Laboral</li>
                <li>Datos Personales</li>
                <li>Contacto Personal</li>
                <li>Contacto Institucional</li>
            </ul>
            <div style="height: 240px;" class="form-horizontal col-sm-12">
                <br>
                <div class="widget">
                    <div class="widget-simple themed-background-default">
                            <a href="#" id="aFotoPerfilTurnAndExceptRelaboral">
                                <img id="imgFotoPerfilTurnAndExceptRelaboral" class="img-rounded pull-right img-perfil">
                            </a>
                            <h4 class="widget-content">
                                <div class="col-sm-5">
                                    <dl class="dl-horizontal" STYLE="color: white;font-size: 13px;">
                                        <dt class="dtNombresTurnAndExcept">Nombres:</dt><dd class="ddNombresTurnAndExcept"></dd>
                                        <dt class="dtCIAndNumComplementoExpdTurnAndExcept">CI:</dt><dd class="ddCIAndNumComplementoExpdTurnAndExcept"></dd>
                                        <dt id="dtCargoTurnAndExcept">Cargo:</dt><dd id="ddCargoTurnAndExcept"></dd>
                                        <dt id="dtProcesoTurnAndExcept">Proceso:</dt><dd id="ddProcesoTurnAndExcept"></dd>
                                        <dt id="dtFinanciamientoTurnAndExcept">Financiamiento:</dt><dd id="ddFinanciamientoTurnAndExcept"></dd>
                                        <dt id="dtGerenciaTurnAndExcept">Gerencia:</dt><dd id="ddGerenciaTurnAndExcept"></dd>
                                        <dt id="dtDepartamentoTurnAndExcept">Departamento:</dt><dd id="ddDepartamentoTurnAndExcept"></dd>
                                    </dl>
                                </div>
                                <div class="col-sm-5">
                                    <dl class="dl-horizontal" STYLE="color: white;font-size: 13px;">
                                        <dt id="dtUbicacionTurnAndExcept">Ubicaci&oacute;n:</dt><dd id="ddUbicacionTurnAndExcept"></dd>
                                        <dt id="dtItemTurnAndExcept">&Iacute;tem:</dt><dd id="ddItemTurnAndExcept"></dd>
                                        <dt id="dtNivelSalarialTurnAndExcept">Nivel Salarial:</dt><dd id="ddNivelSalarialTurnAndExcept"></dd>
                                        <dt id="dtHaberTurnAndExcept">Haber:</dt><dd id="ddHaberTurnAndExcept"></dd>
                                        <dt id="dtFechaIngTurnAndExcept">Fecha Ingreso:</dt><dd id="ddFechaIngTurnAndExcept"></dd>
                                        <dt id="dtFechaIniTurnAndExcept">Fecha Inicio:</dt><dd id="ddFechaIniTurnAndExcept"></dd>
                                        <dt id="dtFechaIncorTurnAndExcept">Fecha Incorporaci&oacute;n:</dt><dd id="ddFechaIncorTurnAndExcept"></dd>
                                        <dt id="dtFechaFinTurnAndExcept">Fecha Finalizaci&oacute;n:</dt><dd id="ddFechaFinTurnAndExcept"></dd>
                                        <dt id="dtEstadoDescripcionTurnAndExcept">Estado:</dt><dd id="ddEstadoDescripcionTurnAndExcept"></dd>
                                        <dt id="dtFechaBajaTurnAndExcept">Fecha Baja:</dt><dd id="ddFechaBajaTurnAndExcept"></dd>
                                        <dt id="dtMotivoBajaTurnAndExcept">Motivo Baja:</dt><dd id="ddMotivoBajaTurnAndExcept"></dd>
                                        <dt id="dtObservacionTurnAndExcept">Observaciones:</dt><dd id="ddObservacionTurnAndExcept"></dd>
                                    </dl>
                                </div>
                            </h4>
                    </div>
                </div>
            </div>
            <div style="display: none;" class="form-horizontal col-sm-12">
                <br>

                <div class="widget">
                    <div class="widget-simple themed-background-default">
                        <a href="#" id="aFotoPerfilTurnAndExcept">
                            <img id="imgFotoPerfilTurnAndExcept" class="img-rounded pull-right img-perfil">
                        </a>
                        <h4 class="widget-content">
                            <div>
                                <dl class="dl-horizontal" STYLE="color: white;font-size: 13px;">
                                    <dt id="dtNombresTurnAndExcept">Nombres y Apellidos:</dt>
                                    <dd id="ddNombresTurnAndExcept"></dd>
                                    <dt id="dtTipoDeDocumentoTurnAndExcept"></dt>
                                    <dd id="ddNumeroDeDocumentoTurnAndExcept"></dd>
                                    <dt id="dtNacionalidadTurnAndExcept">Nacionalidad:</dt>
                                    <dd id="ddNacionalidadTurnAndExcept"></dd>
                                    <dt id="dtLugarDeNacimientoTurnAndExcept">Lugar de Nacimiento:</dt>
                                    <dd id="ddLugarDeNacimientoTurnAndExcept"></dd>
                                    <dt id="dtFechaDeNacimientoTurnAndExcept">Fecha de Nacimiento:</dt>
                                    <dd id="ddFechaDeNacimientoTurnAndExcept"></dd>
                                </dl>
                            </div>
                        </h4>
                    </div>
                </div>
            </div>
            <div style="display: none;" class="form-horizontal col-sm-12">
                <br>

                <div class="widget">
                    <div class="widget-simple themed-background-default">
                        <a href="#" id="aFotoPerfilContactoPerTurnAndExcept"><img id="imgFotoPerfilContactoPerTurnAndExcept"
                                                                     class="img-rounded pull-right img-perfil"></a>
                        <h4 class="widget-content">
                            <div>
                                <dl class="dl-horizontal" STYLE="color: white;font-size: 13px;">
                                    <dt id="dtDireccionTurnAndExcept">Direcci&oacute;n:</dt>
                                    <dd id="ddDireccionTurnAndExcept"></dd>
                                    <dt id="dtTelefonoFijoTurnAndExcept">Tel&eacute;fono Fijo:</dt>
                                    <dd id="ddTelefonoFijoTurnAndExcept"></dd>
                                    <dt id="dtCelularPerTurnAndExcept">Celular Personal:</dt>
                                    <dd id="ddCelularPerTurnAndExcept"></dd>
                                    <dt id="dtEmailPerTurnAndExcept">E-Mail Personal:</dt>
                                    <dd id="ddEmailPerTurnAndExcept"></dd>
                                    <dt id="dtAuxiliar1TurnAndExcept">&nbsp;</dt>
                                    <dd id="ddAuxiliar1TurnAndExcept">&nbsp;</dd>
                                </dl>
                            </div>
                        </h4>
                    </div>
                </div>
            </div>
            <div style="display: none;" class="form-horizontal col-sm-12">
                <br>

                <div class="widget">
                    <div class="widget-simple themed-background-default">
                        <a href="#" id="aFotoPerfilContactoInstTurnAndExcept"><img id="imgFotoPerfilContactoInstTurnAndExcept"
                                                                      class="img-rounded pull-right img-perfil"></a>
                        <h4 class="widget-content">
                            <div>
                                <dl class="dl-horizontal" STYLE="color: white;font-size: 13px;">
                                    <dt id="dtTelefonoInstTurnAndExcept">Tel&eacute;fono Inst.:</dt>
                                    <dd id="ddTelefonoInstTurnAndExcept"></dd>
                                    <dt id="dtCelularInstTurnAndExcept">Celular Corporativo:</dt>
                                    <dd id="ddCelularInstTurnAndExcept"></dd>
                                    <dt id="dtTelefonoFaxTurnAndExcept">Fax:</dt>
                                    <dd id="ddTelefonoFaxTurnAndExcept"></dd>
                                    <dt id="dtInternoInstTurnAndExcept">N&uacute;mero Interno:</dt>
                                    <dd id="ddInternoInstTurnAndExcept"></dd>
                                    <dt id="dtEmailInstTurnAndExcept">E-Mail Institucional:</dt>
                                    <dd id="ddEmailInstTurnAndExcept"></dd>
                                </dl>
                            </div>
                        </h4>
                    </div>
                </div>
            </div>
        </div>

        <br>
        <!-- Contenido referente al calendario laboral y gestión de horarios -->
        <div id="page-content">
            <!-- FullCalendar Content -->
            <div class="block block-alt-noborder full">
                <div class="block-title">
                    <div class="block-options pull-right">
                        <a id="btnImprimirCalendarioLaboralAndExcept" class="btn btn-alt btn-sm btn-default" title="Imprimir Calendario" data-toggle="tooltip" href="javascript:void(0)" data-original-title="Imprimir">
                            <i class="fa fa-print"></i>
                        </a>
                    </div>
                    <h2>
                        <strong><span id="spanPrefijoCalendarioLaboral"></span></strong>
                        Calendario de Turnos Laborales
                        <span id="spanSufijoCalendarioLaboral"></span>
                    </h2>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div id="calendar"></div>
                    </div>
                    </br>
                    <div class="col-md-12" id="divCalendarioDetalles">
                        <div class="block block-alt-noborder full">
                            <div class="block-title">
                                <div class="block-options pull-right">
                                    <a id="btnImprimirCalendarioDetalle" class="btn btn-alt btn-sm btn-default"
                                       title="Imprimir Calendario Detalle" data-toggle="tooltip" href="javascript:void(0)"
                                       data-original-title="Imprimir">
                                        <i class="fa fa-print"></i>
                                    </a>
                                </div>
                                <h2><strong>Calendario</strong> Detalle</h2>
                            </div>
                            <div>
                                <div id="divGridCalendario"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="divGrupoBotonesTurnAndExcept" class="btn-group">
                    <button id="btnCancelarTurnAndExcept" class="btnCancelarTurnAndExcept btn btn-warning"  type="button"><i class="fa fa-repeat"></i> Cancelar / Volver a Listado Principal</button>
                </div>
            </div>
        </div>
        <!-- END FullCalendar Block -->
        <!-- END FullCalendar Content -->
    </form>
</div>
</div>
<div style="display: none" class="modal fade bs-example-modal-lg" id="popupDescripcionHorario" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <form class="form-horizontal" id="testForm_perfil" data-toggle="validator" onsubmit="return false;"/>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="tituloModal">Horario</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <input type="hidden" name="perfil_id" id="perfil_id" value="">
                            <div class="panel-heading">
                                DATOS DEL HORARIO SELECCIONADO
                            </div>
                            <div class="panel-body form-horizontal">
                                <div class="form-group">
                                    <label class="col-sm-3 control-label" for="txtNombreHorario">Nombre Horario:</label>
                                    <div class="col-md-6" form-group>
                                        <input type="text" id="txtNombreHorario" class="form-control" readonly>
                                    </div>
                                </div>
                                <div class="form-group" id="divNombreAlternativoHorario">
                                    <label class="col-sm-3 control-label" for="txtNombreAlternativoHorario">Nombre Alternativo:</label>
                                    <div class="col-md-6" form-group>
                                        <textarea id="txtNombreAlternativoHorario" class="form-control" readonly></textarea>
                                    </div>
                                </div>
                                <div class="form-group" id="divColorHorario">
                                    <label class="col-sm-3 control-label" for="txtColorHorario">Color:</label>
                                    <div class="col-md-6" form-group>
                                        <input type="text" id="txtColorHorario" value="#FFFFFF" class="form-control" readonly>
                                    </div>
                                </div>
                                <fieldset>
                                    <legend><i class="fa fa-angle-right"></i> Horario Entrada / Salida</legend>
                                    <div class="form-group">
                                        <div class="div-calendario-laboral" id="divHoraEntHorario">
                                            <label class="col-sm-2 control-label" for="txtHoraEntHorario">Entrada:</label>
                                            <div class="col-md-2"  form-group>
                                                <input id="txtHoraEntHorario" name="txtHoraEntHorario" placeholder="Hora de entrada." class="form-control" type="text" readonly>
                                            </div>
                                        </div>
                                        <div class="div-calendario-laboral" id="divHoraSalHorario">
                                            <label class="col-sm-2 control-label" for="txtHoraSalHorario">Salida:</label>
                                            <div class="col-md-2"  form-group>
                                                <input id="txtHoraSalHorario" name="txtHoraSalHorario" class="form-control" type="text" readonly>
                                            </div>
                                        </div>
                                        <label class="col-sm-2 control-label" for="txtHorasLaborales">Horas Laborales:</label>
                                        <div class="col-md-2">
                                            <input id="txtHorasLaborales" name="txtHorasLaborales" placeholder="Horas Laborales." type="text" class="form-control" readonly>
                                        </div>
                                    </div>
                                </fieldset>
                                <fieldset>
                                    <legend><i class="fa fa-angle-right"></i> Rango Control Marcaciones</legend>
                                    <div class="form-group">
                                        <div class="div-calendario-laboral" id="divHoraInicioRangoEnt">
                                            <label class="col-sm-3 control-label" for="txtHoraInicioRangoEnt">Inicio Entrada:</label>
                                            <div class="col-md-3">
                                                <input id="txtHoraInicioRangoEnt" name="txtHoraInicioRangoEnt" placeholder="Hora de entrada." class="form-control" type="text" readonly>
                                            </div>
                                        </div>
                                        <div class="div-calendario-laboral" id="divHoraFinalizacionRangoEnt">
                                            <label class="col-sm-3 control-label" for="txtHoraFinalizacionRangoEnt">Finalizaci&oacute;n Entrada:</label>
                                            <div class="col-md-3">
                                                <input id="txtHoraFinalizacionRangoEnt" name="txtHoraFinalizacionRangoEnt" class="form-control" type="text" readonly>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="div-calendario-laboral" id="divHoraInicioRangoSal">
                                            <label class="col-sm-3 control-label" for="txtHoraInicioRangoSal">Inicio Salida:</label>
                                            <div class="col-md-3">
                                                <input id="txtHoraInicioRangoSal" name="txtHoraInicioRangoSal" placeholder="Hora de inicio de salida." class="form-control" type="text" readonly>
                                            </div>

                                        </div>
                                        <div class="div-calendario-laboral" id="divHoraFinalizacionRangoSal">
                                            <label class="col-sm-3 control-label" for="txtHoraFinalizacionRangoSal">Fin Salida:</label>
                                            <div class="col-md-3">
                                                <input id="txtHoraFinalizacionRangoSal" name="txtHoraFinalizacionRangoSal" placeholder="Hora de finalizaci&oacute;n de salida." class="form-control" type="text" readonly>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="div-calendario-laboral" id="divPermitirCruce">
                                            <label class="col-sm-3 control-label" for="txtPermitirCruce">¿Permitir
                                                Cruce?:</label>
                                            <div class="col-md-3">
                                                <input type="checkbox" id="chkPermitirCruce" onclick="return false;">
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                                <fieldset>
                                    <legend><i class="fa fa-angle-right"></i> Rango Fechas</legend>
                                    <div class="form-group">
                                        <div class="div-calendario-laboral" id="divHorarioFechaIni">
                                            <label class="col-sm-3 control-label" for="txtHorarioFechaIni">Fecha Inicio:</label>
                                            <div class="col-md-3">
                                                <input id="txtHorarioFechaIni" name="txtHorarioFechaIni" class="form-control input-datepicker" placeholder="Desde" data-date-format="dd-mm-yyyy" type="text">
                                            </div>
                                        </div>
                                        <div class="div-calendario-laboral" id="divHorarioFechaFin">
                                            <label class="col-sm-3 control-label" for="txtHorarioFechaFin">Fecha Fin:</label>
                                            <div class="col-md-3">
                                                <input id="txtHorarioFechaFin" name="txtHorarioFechaFin" class="form-control input-datepicker" placeholder="Hasta" data-date-format="dd-mm-yyyy" type="text">
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                                <fieldset>
                                    <legend><i class="fa fa-angle-right"></i> Observaciones</legend>
                                    <div class="form-group div-move-relab" id="divObservacion">
                                        <label class="col-md-3 control-label" for="txtObservacion">Observaciones:</label>
                                        <div class="col-md-6">
                                            <textarea id="txtObservacion" name="txtObservacion" class="form-control" placeholder="Observaciones.." readonly></textarea>
                                        </div>
                                    </div>
                                </fieldset>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" id="btnCerrarHorario" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-compress"></i>Cerrar</button>
                <button type="button" id="btnGuardarModificacionHorario" class="btn btn-primary"><i class="fa fa-pencil"></i>Guardar Modificaci&oacute;n de Fechas</button>
                <button type="button" id="btnDescartarHorario" class="btn btn-primary"><i class="gi gi-bin"></i>Descartar</button>
            </div>
            </form>
        </div>
    </div>
</div>
<div style="display: none" id="divMsjeNotificacionError">
    <div id="divMsjePorError">
    </div>
</div>
<div style="display: none" id="divMsjeNotificacionWarning">
    <div id="divMsjePorWarning">
    </div>
</div>
<div style="display: none" id="divMsjeNotificacionSuccess">
    <div id="divMsjePorSuccess">
    </div>
</div>