
	<div class="row">
		<div class="col-lg-12">
			<h3>Adicionar Seguimiento a Contrataciones</h3>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<div class="panel panel-default">
				<div class="panel-heading"> Formulario Basico </div>
				<div class="panel-body"> 
							<form method="post" action="" class="form-horizontal">
								<div class="form-group">
									<label class="col-lg-2 control-label">Unidad Solicitante</label>
									<div class="col-lg-4">
										<?php echo $oficina ?>
									</div>
								</div>
								<div class="form-group">
									<label class="col-lg-2 control-label">Responsable Solicitud</label>
									<div class="col-lg-4">
										<?php echo $usuario ?>
									</div>
								</div>
								<div class="form-group">
									<label class="col-lg-2 control-label">Codigo Proceso</label>
      								<div class="col-lg-4">
        							<input class="form-control" name="codigo_proceso" placeholder="" type="text" required>
      								</div>
								</div>
								<div class="form-group">
									<label class="col-lg-2 control-label">Codigo Cargo</label>
									<div class="col-lg-4">
										<input class="form-control" type="text" name="codigo_cargo" value="" required>
									</div>
								</div>
								<div class="form-group">
									<label class="col-lg-2 control-label">Cargo en Acefalia</label>
									<div class="col-lg-4">
										<?php echo $cargo ?>	
									</div>
								</div>

								<div class="form-group">
									<label class="col-lg-2 control-label">Nro Acefalias</label>
									<div class="col-lg-4">
										<input class="form-control" type="text" name="vacante" value="" required>	
									</div>
								</div>
								<div class="form-group">
									<label class="col-lg-2 control-label">Nro Solicitud</label>
									<div class="col-lg-4">
										<input class="form-control" type="text" name="nro_solicitud" value="" required>	
									</div>
									
								</div>
								<div class="form-group">
									<label class="col-lg-2 control-label">Fecha Solicitud</label>
									<div class="col-lg-4">
										<input type="text" class="form-control" name="f_solicitud" id="f_solicitud" placeholder="click para mostrar calendario" value="<?php echo date("Y-m-d") ?>" required>
									</div>
								</div>
								<div class="form-group">
								     <div class="col-lg-6 col-lg-offset-2">
        								<button class="btn btn-default">Guardar</button>
        								<a href="../" class="btn btn-default">Cancelar</a>
      								</div>
    							</div>
							</form>
				</div>
			</div>
		</div>
	</div>


<script type="text/javascript">
            // When the document is ready
            $(document).ready(function () {
            	$('#f_solicitud').datepicker({
            		format: "yyyy-mm-dd"
            	});  

            });
        </script>