<div class="row">
	<div class="col-lg-12">
		<h3>Seguimiento a Contrataciones</h3>
	</div>
</div>


<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
			<?php echo $this->flashSession->output() ?>
				<div class="table-responsive">
					<table class="table table-striped table-bordered table-hover" id="dataTables-example">
	<thead>
		<tr>
			<th>Nro</th>
			<th>Unidad Solicitante</th>
			<th>Responsable de la Solicitud</th>
			<th>Codigo Proceso</th>
			<th>Codigo Cargo</th>
			<th>Cargo</th>
			<th>Nro Solicitud</th>
			<th>Fecha Solicitud</th>
			<th><a href="/seguimientos/add/" title="adicionar"><i class="fa fa-plus fa-lg"></i></a></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($seguimiento as $p) { ?>
		<tr class="odd gradeA">
			<td><?php echo $p->id ?></td>
			<td><?php echo $p->oficina ?></td>
			<td><?php echo $p->nombre ?></td>
			<td><?php echo $p->codigo_proceso ?></td>
			<td><?php echo $p->codigo_cargo ?></td>
			<td><?php echo $p->cargo ?></td>
			<td><?php echo $p->nro_solicitud ?></td>
			<td><?php echo $p->f_solicitud ?></td>
			<td>
			<a href="../seguimientos/edit/<?php echo $p->id ?>" title="Editar"><i class="fa fa-pencil fa-lg"></i></a> 
			<a href="../seguimientos/delete/<?php echo $p->id ?>" title="Eliminar"><i class="fa fa-trash-o fa-lg"></i></a></td>
		</tr>
		<?php } ?>
	</tbody>
		
	</table>
	
</div>
			</div>
		</div>
		
	</div>
</div>

<script>
	$(document).ready(function() {
		$('#dataTables-example').dataTable();
	});
</script>