<div class="row">
	<div class="col-lg-12">
		<h1>Organigrama</h1>		
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<?php echo $this->flashSession->output() ?>
				<div class="table-responsive">
					<table class="table table-striped table-bordered table-hover" id="dataTables-example">
						<thead>
							<tr>
								<th>Nro</th>
								<th>Unidad</th>
								<th>Sigla</th>
								<th><a href="/organigramas/add/">Adicionar</a></th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($organigrama as $p) { ?>
							<tr class="odd gradeA">
								<td><?php echo $p->id ?></td>
								<td><?php echo $p->unidad_administrativa ?></td>
								<td><?php echo $p->sigla ?></td>
								<td>
									<a href="../organigramas/edit/<?php echo $p->id ?>">Editar</a>
									<a href="../organigramas/delete/<?php echo $p->id ?>">Eliminar</a>
								</td>
							</tr>
							<?php } ?>

						</tbody>
					</table>
				</div>
			</div>
		</div>
		
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<ul id="org" style="display:none">
			<li>
				Food
				<ul>
					<li>Beer</li>
					<li>Vegetables
						<ul>
							<li>Pumpkin</li>
							<li>Aubergine</li>
						</ul>
					</li>
					<li>Fruit
						<ul>
							<li>Apple
								<ul>
									<li>Granny Smith</li>
								</ul>
							</li>
							<li>Berries
								<ul>
									<li>Blueberry</li>
									<li>Otros</li>
									<li>Cucumber</li>
								</ul>
							</li>
						</ul>
					</li>
					<li>Bread</li>
					<li class="collapsed">Chocolate
						<ul>
							<li>Topdeck</li>
							<li>Reese's Cups</li>
						</ul>
					</li>
				</ul>
			</li>
		</ul>            

		<div id="chart" class="orgChart"></div>
	</div>
</div>

<script>
	$(document).ready(function() {
		$('#dataTables-example').dataTable();
	});
</script>
<script>
    jQuery(document).ready(function() {
        $("#org").jOrgChart({
            chartElement : '#chart',
            dragAndDrop  : true
        });
    });
    </script>
    <script>
        jQuery(document).ready(function() {
            
            /* Custom jQuery for the example */
            $("#show-list").click(function(e){
                e.preventDefault();
                
                $('#list-html').toggle('fast', function(){
                    if($(this).is(':visible')){
                        $('#show-list').text('Hide underlying list.');
                        $(".topbar").fadeTo('fast',0.9);
                    }else{
                        $('#show-list').text('Show underlying list.');
                        $(".topbar").fadeTo('fast',1);                  
                    }
                });
            });
            
            $('#list-html').text($('#org').html());
            
            $("#org").bind("DOMSubtreeModified", function() {
                $('#list-html').text('');
                
                $('#list-html').text($('#org').html());
                
                prettyPrint();                
            });
        });
    </script>