<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    PROCESO DE CONTRATACIÓN
                </div>
                <div class="panel-body">
                    <form method="post" action="" class="form-horizontal" id="testForm" enctype="multipart/form-data">
                        <div class="row">
                            <div class="col-lg-6">

                                <div class="form-group">
                                    <label class="col-lg-4 control-label">Cargos</label>
                                    <div class="col-lg-8">
                                        <?php echo $cargos ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-lg-4 control-label">Carreras</label>
                                    <div class="col-lg-8">
                                        <?php foreach ($carreras as $v){ ?>
                                            <div class="checkbox">
                                                <label for="example-checkbox1">
                                                    <input id="carrera_check" name="carrera_check[]" value="<?php echo $v->id ?>" type="checkbox">
                                                    <?php echo $v->carrera?>
                                                </label>
                                            </div>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <div class="col-lg-12" align="center">
                                    <button type="submit" class="btn btn-primary" id="guardar">Guardar</button>
                                    <a href="../" class="btn btn-primary">Cancelar</a>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<style type="text/css">
    .datepicker {
        z-index: 1151 !important;
    }
</style>