<h1>Editar Resolución</h1>
<form method="post" action="">
<input type="hidden" name="id" value="<?php echo $resolucion->id ?>">
	<div>
		<label>Tipo Resolución:</label>
		<input type="text" name="tipo_resolucion" value="<?php echo $resolucion->tipo_resolucion ?>">	
	</div>
	<div>
		<label>Número Resolución</label>
		<input type="text" name="numero_res" value="<?php echo $resolucion->numero_res ?>">	
	</div>
	<div>
		<label>Fecha Emisión</label>
		<input type="text" name="fecha_emi" id="fecha_emi" value="<?php echo $resolucion->fecha_emi ?>">	
	</div>
	<div>
		<label>Fecha Aprobación</label>
		<input type="text" name="fecha_apr" id="fecha_apr" value="<?php echo $resolucion->fecha_apr ?>">	
	</div>
	<div>
		<button>Guardar</button>
		<a href="../">Cancelar</a>
	</div>
</form>

<script type="text/javascript">
            // When the document is ready
            $(document).ready(function () {
            	$('#fecha_emi, #fecha_apr').datepicker({
            		format: "yyyy-mm-dd"
            	});  

            });
</script>