<div class="row">
	<div class="col-lg-12">
		<h1>Procesos</h1>		
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
			<?php echo $this->flashSession->output() ?>
				<div class="table-responsive">
					<table class="table table-striped table-bordered table-hover" id="dataTables-example">
						<thead>
							<tr>
								<th>Nro</th>
								<th>Proceso</th>
								<th>Descripción</th>
								<th><a href="/procesos/add/">Adicionar</a></th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($proceso as $p) { ?>
							<tr class="odd gradeA">
								<td><?php echo $p->id ?></td>
								<td><?php echo $p->proceso ?></td>
								<td><?php echo $p->descripcion ?></td>
								<td>
									<a href="../procesos/edit/<?php echo $p->id ?>">Editar</a>
									<a href="../procesos/delete/<?php echo $p->id ?>">Eliminar</a>
								</td>
							</tr>
							<?php } ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		
	</div>
</div>

<script>
	$(document).ready(function() {
		$('#dataTables-example').dataTable();
	});
</script>