<?php clearstatcache(); ?>
<div class="row">
    <div class="col-sm-12">
        <div class="panel">
            <div class="panel-heading">
                <h3><i class="fa-lg fa fa-users "></i> Personas registradas en el sistema</h3>
                <!-- <div class="options">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#domshortcuttiles"><i class="fa fa-users"></i></a></li>
                        <li><a data-toggle="tab" href="#codeshortcuttiles"><i class="fa fa-code"></i></a></li>
                    </ul>
                </div> -->

            </div>
            <div class="panel-body">        
                <div class="tab-content">                    
                        <div class="row ">
                            <div class="col-md-12">
                                <?php echo $this->flashSession->output(); ?>        
                            </div>
                        </div>
                        <div class="row">  
                            <div class="col-lg-12">                        
                                <?php //echo $this->flashSession->output() ?>
                                <div class="pull-right">
                                    <div>
                                        <a href="/personas/nuevo" class="btn btn-sm btn-primary" title="registrar persona" ><i class="fa fa-plus"></i> Nuevo</a>
                                        <a href="javascript:;" id="edit" class="btn btn-sm btn-default" title="Editar Persona" ><i class="fa fa-pencil"></i> Editar</a>
                                        <a href="javascript:;" id="delete" class="btn btn-sm btn-danger" title="Eliminar Persona" ><i class="fa fa-trash-o"></i> Eliminar</a>
                                        <!-- <a href="javascript:;" id="excel" class="btn btn-sm btn-green" title="Imprimir registro" ><i class="fa fa-table"></i> Excel</a> -->
                                    </div>
                                </div>                
                            </div>        
                        </div>

                        <div class="row">
                            <div class="col-lg-12">
                                <div id="jqxgrid" style="height: 550px; width: 100%;" ></div>
                            </div>
                        </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
