<script type="text/javascript">
function utf8_encode(argString) {
  //  discuss at: http://phpjs.org/functions/utf8_encode/
  // original by: Webtoolkit.info (http://www.webtoolkit.info/)
  // improved by: Kevin van Zonneveld (http://kevin.vanzonneveld.net)
  // improved by: sowberry
  // improved by: Jack
  // improved by: Yves Sucaet
  // improved by: kirilloid
  // bugfixed by: Onno Marsman
  // bugfixed by: Onno Marsman
  // bugfixed by: Ulrich
  // bugfixed by: Rafal Kukawski
  // bugfixed by: kirilloid
  //   example 1: utf8_encode('Kevin van Zonneveld');
  //   returns 1: 'Kevin van Zonneveld'

  if (argString === null || typeof argString === 'undefined') {
    return '';
  }

  var string = (argString + ''); // .replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  var utftext = '',
    start, end, stringl = 0;

  start = end = 0;
  stringl = string.length;
  for (var n = 0; n < stringl; n++) {
    var c1 = string.charCodeAt(n);
    var enc = null;

    if (c1 < 128) {
      end++;
    } else if (c1 > 127 && c1 < 2048) {
      enc = String.fromCharCode(
        (c1 >> 6) | 192, (c1 & 63) | 128
      );
    } else if ((c1 & 0xF800) != 0xD800) {
      enc = String.fromCharCode(
        (c1 >> 12) | 224, ((c1 >> 6) & 63) | 128, (c1 & 63) | 128
      );
    } else { // surrogate pairs
      if ((c1 & 0xFC00) != 0xD800) {
        throw new RangeError('Unmatched trail surrogate at ' + n);
      }
      var c2 = string.charCodeAt(++n);
      if ((c2 & 0xFC00) != 0xDC00) {
        throw new RangeError('Unmatched lead surrogate at ' + (n - 1));
      }
      c1 = ((c1 & 0x3FF) << 10) + (c2 & 0x3FF) + 0x10000;
      enc = String.fromCharCode(
        (c1 >> 18) | 240, ((c1 >> 12) & 63) | 128, ((c1 >> 6) & 63) | 128, (c1 & 63) | 128
      );
    }
    if (enc !== null) {
      if (end > start) {
        utftext += string.slice(start, end);
      }
      utftext += enc;
      start = end = n + 1;
    }
  }

  if (end > start) {
    utftext += string.slice(start, stringl);
  }

  return utftext;
};

$(document).ready(function () {
		var source =
		{
			datatype: "json",
			datafields: [
				{ name: 'id'},
				{ name: 'p_nombre'},
                                { name: 's_nombre'},
                                { name: 'p_apellido'},
                                { name: 's_apellido'},
                                { name: 'ci', type: 'string'},
                                { name: 'fecha_nac', format: 'date'},
				{ name: 'expd'},
				{ name: 'fecha_emi'},
				{ name: 'fecha_apr', format: 'date'}
			],
			url: '../../personal/list',
			cache: false
		};
		var dataAdapter = new $.jqx.dataAdapter(source);
		cargar();
		function cargar(){
                    $("#jqxgrid").jqxGrid(
		{
            theme : 'oasis',
		width: '90%',
		source: dataAdapter,
		sortable: true,
		altRows: true,
		pageable: true,
		pagerMode: 'advanced',
		showfilterrow: true,
		filterable: true,
		columns: [
                    { text: 'Nro', displayfield: 'nro',columntype: 'number',width: 30, sortable:false, filterabel: false},
                    { text: 'Nro', datafield: 'id',filtertype: 'input', width: '5%', hidden: true},
                    { text: '1o Nombre', datafield: 'p_nombre', filtertype: 'input',width: '13%'},
                    { text: '2o Nombre', datafield: 's_nombre', filtertype: 'input',width: '13%'},
                    { text: '1o Apellido', datafield: 'p_apellido', filtertype: 'input',width: '13%'},
                    { text: '2o Apellido', datafield: 's_apellido', filtertype: 'input',width: '13%'},
                    { text: 'Doc. Ident.', datafield: 'ci', type: 'string',filtertype: 'input',width: '11%' },
                    { text: 'EXP', datafield: 'expd', type: 'string',filtertype: 'input',width: '5%' },
                    { text: 'Fecha Nac.', datafield: 'fecha_nac', format: 'date', filtertype: 'range', cellsformat: 'yyyy', width: '11%'},
                    { text: 'Editar', datafield: 'Editar', width: '7%',sortable: false, filterable: false, columntype: 'button', cellsrenderer: function () {
                        return "Editar";
                    }, buttonclick: function (row) {
                        editrow = row;
                        var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
                        //window.open("/archivo/gestion/", "_blank");
                        document.location.href = '/personal/editar/'+dataRecord.id;
                        /*// open the popup window when the user clicks a button.
                        editrow = row;
                        var offset = $("#jqxgrid").offset();
                        $("#popupWindow").jqxWindow({ position: { x: parseInt(offset.left) + 60, y: parseInt(offset.top) + 60 } });
                        // get the clicked row's data and initialize the input fields.
                        var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
                        $("#titulo").text("Editar");
                        $("#id").val(dataRecord.id);
                        $("#tipo_resolucion").val(dataRecord.tipo_resolucion);
                        $("#numero_res").val(dataRecord.numero_res);
                        var fecha=dataRecord.fecha_emi;
                        fecha=fecha.replace("-", "/").replace("-", "/");	  
                        fecha= new Date(fecha);
                        fecha.setDate(fecha.getDate());
                        $("#fecha_emi").jqxDateTimeInput('setDate', fecha);
                        var fecha=dataRecord.fecha_apr;
                        fecha=fecha.replace("-", "/").replace("-", "/");	  
                        fecha= new Date(fecha);
                        fecha.setDate(fecha.getDate());
                        $("#fecha_apr").jqxDateTimeInput('setDate', fecha);
                        // show the popup window.
                        $("#popupWindow").jqxWindow('open');*/
                    }
                    },
                    /*{ text: 'Imprimir', datafield: 'Imprimir',width:80, sortable:false, filterable: false, columntype: 'button', cellsrenderer: function () {
                        return "Imprimir";
                    }, buttonclick: function (row) {
                        editrow = row;
                        
                        //var rows = $('#jqxgrid').jqxGrid('getdisplayrows');
                        columna = new Object(); 
                        row_id = $('#jqxgrid').jqxGrid('getcolumn','id');
                        p_nombre = $('#jqxgrid').jqxGrid('getcolumn','p_nombre');
                        s_nombre = $('#jqxgrid').jqxGrid('getcolumn','s_nombre');
                        p_apellido = $('#jqxgrid').jqxGrid('getcolumn','p_apellido');
                        s_apellido = $('#jqxgrid').jqxGrid('getcolumn','s_apellido');
                        ci = $('#jqxgrid').jqxGrid('getcolumn','ci');
                        fecha_nac = $('#jqxgrid').jqxGrid('getcolumn','fecha_nac');
                        columna[p_nombre.datafield] = {text: p_nombre.text, hidden: p_nombre.hidden};
                        columna[row_id.datafield] = {text: row_id.text, hidden: row_id.hidden};
                        columna[s_nombre.datafield] = {text: s_nombre.text, hidden: s_nombre.hidden};
                        columna[p_apellido.datafield] = {text: p_apellido.text, hidden: p_apellido.hidden};
                        columna[s_apellido.datafield] = {text: s_apellido.text, hidden: s_apellido.hidden};
                        columna[ci.datafield] = {text: ci.text, hidden: ci.hidden};
                        columna[fecha_nac.datafield] = {text: fecha_nac.text, hidden: fecha_nac.hidden};
                        //alert(columna['id']['text']);
                        //var array_columna ={text: columna.text, datafield: columna.datafield, hidden: columna.hidden}
                        
                        var rows = $('#jqxgrid').jqxGrid('getrows');//alert(rows[0]['p_nombre']);
                        var n_rows = rows.length;
                        var json_rows = JSON.stringify(rows);
                        var json_columns = JSON.stringify(columna);
                        window.open("/personal/imprimir/"+n_rows+"/"+json_rows+"/"+json_columns, "_blank");
                    }
                    },*/
                    { text: 'Eliminar', datafield: 'Eliminar',width:'7%', sortable:false, filterable: false, columntype: 'button', cellsrenderer: function () {
                        return "Eliminar";
                    }, buttonclick: function (row) {
                        editrow = row;
                        var offset = $("#jqxgrid").offset();
                        $("#popupWindow_delete").jqxWindow({ position: { x: parseInt(offset.left) + 60, y: parseInt(offset.top) + 60 } });
                        var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
                        $("#id").val(dataRecord.id);
                        $("#popupWindow_delete").jqxWindow('open');
                    }
                    },
                    { text: 'Ver', datafield: 'Ver',width:'7%', sortable:false, filterable: false, columntype: 'button', cellsrenderer: function () {
                        return "Ver";
                    }, buttonclick: function (row) {
                        editrow = row;
                        var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
                        document.location.href = '/personal/visualizar/'+dataRecord.id;
                    }
                    }
		]
                });
                }
		// initialize the popup window and buttons.
            $("#popupWindow").jqxWindow({
                width: 850,height:500, resizable: false,  isModal: true, autoOpen: false, cancelButton: $("#Cancel"), modalOpacity: 0.01           
            });
            $("#popupWindow_delete").jqxWindow({
                width: 400, resizable: false,  isModal: true, autoOpen: false, cancelButton: $("#Cancel"), modalOpacity: 0.01           
            });
            // update the edited row when the user clicks the 'Save' button.
            $("#imprimir").click(function(){
                columna = new Object();
                filtros = new Object();
                row_id = $('#jqxgrid').jqxGrid('getcolumn','id');
                p_nombre = $('#jqxgrid').jqxGrid('getcolumn','p_nombre');
                s_nombre = $('#jqxgrid').jqxGrid('getcolumn','s_nombre');
                p_apellido = $('#jqxgrid').jqxGrid('getcolumn','p_apellido');
                s_apellido = $('#jqxgrid').jqxGrid('getcolumn','s_apellido');
                ci = $('#jqxgrid').jqxGrid('getcolumn','ci');
                fecha_nac = $('#jqxgrid').jqxGrid('getcolumn','fecha_nac');
                expd = $('#jqxgrid').jqxGrid('getcolumn','expd');
                columna[p_nombre.datafield] = {text: p_nombre.text, hidden: p_nombre.hidden};
                columna[row_id.datafield] = {text: row_id.text, hidden: row_id.hidden};
                columna[s_nombre.datafield] = {text: s_nombre.text, hidden: s_nombre.hidden};
                columna[p_apellido.datafield] = {text: p_apellido.text, hidden: p_apellido.hidden};
                columna[s_apellido.datafield] = {text: s_apellido.text, hidden: s_apellido.hidden};
                columna[ci.datafield] = {text: ci.text, hidden: ci.hidden};
                columna[expd.datafield] = {text: expd.text, hidden: expd.hidden};
                columna[fecha_nac.datafield] = {text: fecha_nac.text, hidden: fecha_nac.hidden};
                var rows = $('#jqxgrid').jqxGrid('getrows');//alert(rows[0]['p_nombre']);
                var filterGroups = $('#jqxgrid').jqxGrid('getfilterinformation');
                var counter = 0;
                for (var i = 0; i < filterGroups.length; i++) {
                    var filterGroup = filterGroups[i];
                    var filters = filterGroup.filter.getfilters();
                    for (var j = 0; j < filters.length; j++) {
                        if (j>0){
                            counter++;
                        }
                        var indice = i+counter;                    
                        filtros[indice] = {columna: filterGroup.filtercolumn, valor: filters[j].value,
                                           condicion: filters[j].condition, tipo: filters[j].type};
                    }
                }
                var n_rows = rows.length;
                var json_filter = JSON.stringify(filtros);
                //var json_rows = JSON.stringify(rows);
                var json_columns = JSON.stringify(columna);
                //json_rows = btoa(utf8_encode(json_rows));
                json_columns = btoa(utf8_encode(json_columns));
                json_filter = btoa(utf8_encode(json_filter));
                //json_rows = json_rows.replace(/\+/g, '-').replace(/\//g, '_').replace(/\=+$/, '');
                json_columns= json_columns.replace(/\+/g, '-').replace(/\//g, '_').replace(/\=+$/, '');
                json_filter= json_filter.replace(/\+/g, '-').replace(/\//g, '_').replace(/\=+$/, '');
                window.open("/personal/imprimir/"+n_rows+"/"+json_columns+"/"+json_filter, "_blank");
            });
            $("#add").click(function(){
                //$("#page-content").load('../../personal/registro');
                document.location.href = '../../personal/registro';
            	/*$("#titulo").text("Adicionar");
            	$("#id").val("");
            	$("#tipo_resolucion").val("");
            	$("#numero_res").val("");
            	$("#popupWindow").jqxWindow('open');
            	$("#fecha_emi").jqxDateTimeInput({width: '250px', height: '25px',formatString:'yyyy-MM-dd'});
            	fecha= new Date();
  				fecha.setDate(fecha.getDate());
				$("#fecha_emi").jqxDateTimeInput('setDate', fecha);
				fecha= new Date();
  				fecha.setDate(fecha.getDate());
				$("#fecha_apr").jqxDateTimeInput('setDate', fecha);*/
            });

            $("#Save").click(function () {
            	var fecha_apr = $('#fecha_apr').jqxDateTimeInput('getDate');
            	var fecha_emi = $('#fecha_emi').jqxDateTimeInput('getDate');
            	var v=$.ajax({
                    	url:'../../resoluciones/save/',
                    	type:'POST',
                    	datatype: 'json',
			data:{id:$("#id").val(),tipo_resolucion:$("#tipo_resolucion").val(),numero_res:$("#numero_res").val(),fecha_apr:fecha_apr,fecha_emi:fecha_emi},
			success: function(data) { cargar(); //alert(data); 
			}, //mostramos el error
			error: function() { alert('Se ha producido un error Inesperado'); }
		});
                $("#popupWindow").jqxWindow('hide');
               // }
            });

            $("#Eliminar").click(function () {
            	if (editrow >= 0) {
                    var v=$.ajax({
                    	url:'../../personal/delete/',
                    	type:'POST',
                    	datatype: 'json',
						data:{id:$("#id").val()},
						success: function(data) { cargar(); //alert('Guardado Correctamente'); 
												}, //mostramos el error
						error: function() { alert('Se ha producido un error Inesperado'); }
					});
					//$('#jqxgrid').jqxGrid();
                    $("#popupWindow_delete").jqxWindow('hide');
                }
            });

            // create a jqxDateTimeInput.
            //var f='2014-01-01'; 
               	$("#fecha_emi").jqxDateTimeInput({width: '250px', height: '25px',formatString:'yyyy-MM-dd'});
                $("#fecha_apr").jqxDateTimeInput({width: '250px', height: '25px',formatString:'yyyy-MM-dd'});
	});
</script>

<div class="row">
	<div class="col-lg-12">
            <h1><b>Lista de Personal</b></h1>		
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<?php //echo $this->flashSession->output() ?>
				<div style="margin-left: 5px;">
					<div>
						<input id="add" type="button" value=" (+) Adicionar" />
                                                <input id="imprimir" type="button" value="Imprimir" />
					</div>
				</div>
				<br>
				<div class="table-responsive">
					<div id="jqxgrid"></div>
				</div>

				<div style="margin-top: 30px;">
            		<div id="cellbegineditevent"></div>
            		<div style="margin-top: 10px;" id="cellendeditevent"></div>
       			</div>
				<div id="popupWindow">
					<div id="titulo">Editar</div>
					<div style="overflow: hidden;">
						<table>
							<tr>
								<td align="right">id:</td>
								<td align="left"><input id="id" name="id" type="hidden" /></td>
							</tr>
							<tr>
								<td align="right">Tipo Resolución:</td>
								<td align="left"><input id="tipo_resolucion" name="tipo_resolucion" type="text" /></td>
							</tr>
							<tr>
								<td align="right">Numero Resolución:</td>
								<td align="left"><input id="numero_res" name="numero_res" type="text" /></td>
							</tr>
							<tr>
								<td align="right">Fecha Emisión:</td>
								<td align="left"><div id='fecha_emi'></div></td>
							</tr>
							<tr>
								<td align="right">Fecha Aprobación:</td>
								<td align="left"><div id='fecha_apr'></div></td>
							</tr>
							<tr>
								<td align="right"></td>
								<td style="padding-top: 10px;" align="right">
								<input style="margin-right: 5px;" type="button" id="Save" value="Save" />
								<input id="Cancel" type="button" value="Cancel" />
								</td>
							</tr>
						</table>
					</div>
				</div>

				<div id="popupWindow_delete">
					<div>Eliminar</div>
					<div style="overflow: hidden;">
						<table>
							<tr>
								<td align="left">Esta seguro de Eliminar el registro</td>
							</tr>
							<tr>
								<td align="right"></td>
								<td style="padding-top: 10px;" align="right">
								<input style="margin-right: 5px;" type="button" id="Eliminar" value="Eliminar" />
								<input id="Cancel" type="button" value="Cancel" />
								</td>
							</tr>
						</table>
					</div>
				</div>

			</div>
		</div>
		
	</div>
</div>

