<?php
if (isset($_POST['username'])) {
    $user = $_POST['username'];
} else {
    $user = '';
}
?>
<!-- BEGIN ERROR BOX -->
<?php  echo $this->flashSession->output(); ?>
<!--<script src="/assets/js/vendor/jquery-1.11.0.min.js"></script>-->
<script type="text/javascript" src="/js/jqwidgets/scripts/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="/js/login/oasis.login.js"></script>
<script type="text/css" src="/assets/css/bootstrap.min.css"></script>

<div class="alert alert-danger hide" id="divIngreso">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4>Error!</h4>
</div>

<!-- END ERROR BOX -->
<form method="post" class="form-horizontal form-bordered col-md-12">

    <input type="text" name="username" id="username" placeholder="Usuario" value="<?php  echo $user; ?>" class="input-field form-control user" />
    <input type="password" name="password" id="password" placeholder="Contrase&ntilde;a" class="input-field form-control password" />
    <div class="form-group">
        <div class="col-md-1">

        </div>
        <div class="col-md-4 ">
            <button type="submit" class="btn btn-login" >Ingresar</button>
        </div>
        <div class="col-md-1">

        </div>
        <div class="col-md-5">
            <select style="text-align: center" name="modalidad" id="modalidad"  size="1" class="input-field form-control"><option value="0" selected>Consulta</option><option value="1">Administrador</option></select>
        </div>

    </div>
</form>
<div class="login-links">
    <a href="/login/password">¿Olvid&oacute; su contraseña?</a>
    <br>
    <!--<a href="/login/password">No tengo cuenta? <strong>Registrarme</strong></a>-->
    <a href="/login/password">No tengo cuenta. <strong>Registrarme</strong></a>
    <br>
    <!--<a href="/login/password">No tengo cuenta? <strong>Registrarme</strong></a>-->
    <a href="/files/manual/ManualSistemaRecursosHumanos13012017.pdf" download="ManualSistRRHH2017.pdf"><i class="fa fa-book"></i> <strong>Manual de Usuario</strong></a>
</div>

