<?php
if (isset($_POST['username'])) {
    $user = $_POST['username'];
} else {
    $user = '';
}
?>
<!-- BEGIN ERROR BOX -->
<?php echo $this->flashSession->output(); ?>
<link rel="stylesheet" href="/assets/css/bootstrap.min.css">
<link rel="stylesheet" href="/assets/css/plugins.css">
<link rel="stylesheet" href="/assets/css/main.css">
<link rel="stylesheet" href="/assets/css/themes.css">
<script src="/assets/js/vendor/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="/js/jqwidgets/scripts/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="/js/login/oasis.password.js"></script>

<div style="display: none;" class="alert alert-success" id="divPasswordSuccess">
    <button type="button" class="close" aria-hidden="true">×</button>
    <h4><i class="fa fa-check-circle"></i> &Eacute;xito</h4>
    <span class="span-alert" id="spanSuccess"></span>
</div>
<div style="display: none;" class="alert alert-info" id="divPasswordInfo">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4><i class="fa fa-info-circle"></i> Importante!</h4>
    <span class="span-alert" id="spanInfo"></span>
</div>
<div style="display: none;" class="alert alert-warning" id="divPasswordWarning">
    <button type="button" class="close" aria-hidden="true">×</button>
    <h4><i class="fa fa-exclamation-circle"></i> Alerta!</h4>
    <span class="span-alert" id="spanWarning"></span>
</div>
<div style="display: none;" class="alert alert-danger" id="divPasswordDanger">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4><i class="fa fa-times-circle"></i> Error!</h4>
    <span class="span-alert" id="spanDanger"></span>
</div>
<!-- END ERROR BOX -->
<form action="#" method="post" onsubmit="return false;">
    <p>Ingrese su direcci&oacute;n de correo institucional y se le enviará un enlace para restablecer la contrase&ntilde;a.</p>
    <input id="email" type="email" value="@viasbolivia.gob.bo" placeholder="Email" name="email" class="input-field" required/>
    <div class="row">
        <div class="col-md-12">
            <!--<button id="btnEnviarEmail" type="submit" class="btn btn-login pull-right btn-reset">Enviar</button>-->
        </div>
    </div>
    <div class="form-group form-actions">
    <div class="col-xs-12 text-center">
        <button id="btnEnviarEmail" class="btn btn-sm btn-default" type="submit">
            <i class="gi gi-envelope fa-2x"></i>
            &nbsp;&nbsp;Enviar&nbsp;&nbsp;
        </button>
    </div>
    </div>
</form>
<div class="login-links">
    <a id="aYaTienesCuenta" href="/login">¿Ya tienes cuenta? <strong>Ingresar</strong></a>
</div>
<div style="display: none;" id="divMsjeNotificacionError">
    <div id="divMsjePorError">
    </div>
</div>
<div style="display: none;" id="divMsjeNotificacionWarning">
    <div id="divMsjePorWarning">
    </div>
</div>
<div style="display: none;"  id="divMsjeNotificacionSuccess">
    <div id="divMsjePorSuccess">
    </div>
</div>