<h2 style="padding-top: 0px; width: 100%;"><b>Clasificaci&oacute;n de Ideas de Negocio</h2>
<div id='divTabAllIdeas'>
<ul>
    <li id="liAll">Listado General</li>
    <li id="liView">Ver</li>
</ul>
<br>
<div style="height: 650px;" class="section" id="divAll">
    <div class="col-md-12">
        <!-- Input Grid Block -->
        <div class="block">
            <!-- Input Grid Title -->
            <div class="block-title">
                <div id='jqxWidgetAll'>
                    <div class="col-md-1">
                        <br/>
                        <label>Gesti&oacute;n:</label>
                    </div>
                    <div class="col-sm-2" id="divGestionGen">
                        <select id="lstGestionGen" class="form-control">
                            <option value="">Seleccionar..</option>
                        </select>
                    </div>
                    <div class="col-sm-2" id="divMesGen">
                        <select id="lstMesGen" class="form-control">
                            <option value="">Seleccionar..</option>
                        </select>
                    </div>
                    <div id="divGridIdeasAll"></div>
                </div>
            </div>
            <!-- END Input Grid Title -->
        </div>
        <!-- END Input Grid Block -->
    </div></div>
<div style="display: none;" class="section" id="divView">
    <h6><b>NOTA: </b>Los datos precedidos de asterisco son requerido de manera obligatoria (*).</h6>
    <div class="form-horizontal col-sm-12">
        <fieldset>
            <legend><i class="fa fa-angle-right"></i> Detalle de la Idea de Negocio</legend>
            <!-- Headings Block -->
            <div class="row">
                <div class="div-ideas" id="divGestionEdit">
                    <label class="col-sm-2 control-label" for="lstGestionEdit">Gesti&oacute;n *:</label>
                    <div class="col-md-2">
                        <select id="lstGestionEdit" class="form-control"><option value="">Seleccionar..</option></select>
                        <span class="help-block" id="helpErrorGestionEdit"></span>
                    </div>
                </div>
                <div class="div-ideas" id="divMesEdit">
                    <label class="col-sm-2 control-label" for="lstMesEdit">Mes *:</label>
                    <div class="col-md-2">
                        <select id="lstMesEdit" class="form-control"><option value="">Seleccionar..</option></select>
                        <span class="help-block" id="helpErrorMesEdit"></span>
                    </div>
                </div>
                <div class="div-ideas" id="divTiposDeNegocioEdit">
                    <label class="col-sm-2 control-label" for="lstTiposDeNegocioEdit">Tipo *:</label>
                    <div class="col-md-2">
                        <select id="lstTiposDeNegocioEdit" class="form-control"><option value="">Seleccionar..</option></select>
                        <span class="help-block" id="helpErrorTiposDeNegocioEdit"></span>
                    </div>
                </div>
            </div>
            <div class="form-group div-ideas" id="divTituloEdit">
                <label class="col-md-3 control-label" for="txtTituloEdit">T&iacute;tulo*:</label>
                <div class="col-md-6">
                    <textarea id="txtTituloEdit" name="txtTituloEdit" class="form-control" placeholder="T&iacute;tulo de la Idea de Negocio.." readonly></textarea>
                </div>
                <span class="help-block" id="helpErrorTituloEdit"></span>
            </div>
            <div class="form-group div-ideas" id="divResumenEdit">
                <label class="col-md-3 control-label" for="txtResumenEdit">Resumen*:</label>
                <div class="col-md-6">
                    <textarea id="txtResumenEdit" name="txtResumenEdit" class="form-control" placeholder="Resumen de la Idea de Negocio.." readonly></textarea>
                </div>
                <span class="help-block" id="helpErrorResumenEdit"></span>
            </div>
            <div class="form-group div-ideas" id="divDescripcionEdit">
                <label class="col-md-3 control-label" for="txtDescripcionEdit">Planteamiento*:</label>
                <div class="col-md-6">
                    <textarea id="txtDescripcionEdit" name="txtDescripcionEdit" class="form-control" placeholder="Planteamiento de la Idea de Negocio.." readonly></textarea>
                </div>
                <span class="help-block" id="helpErrorDescripcionEdit"></span>
            </div>
        </fieldset>
        <fieldset>
            <legend><i class="fa fa-angle-right"></i> &nbsp;</legend>
            <div class="form-group div-control-excepciones" id="divObservacionEdit">
                <label class="col-md-3 control-label" for="txtObservacionEdit" id="lblObservacionEdit">Observaciones:</label>
                <div class="col-md-6">
                    <textarea id="txtObservacionEdit" name="txtObservacionEdit" class="form-control" placeholder="Observaciones.."></textarea>
                </div>
                <span class="help-block" id="helpErrorObservacionEdit"></span>
            </div>
        </fieldset>
        <div class="form-group form-actions">
            <div class="col-md-8 col-md-offset-4">
                <button class="btn btn-sm btn-warning" type="button" id="btnVolverAlListadoPrincipalDesdeEdit">
                    <i class="fa fa-reply"></i>
                    Volver al Listado Principal
                </button>
            </div>
        </div>
        <input type="hidden" id="hdnIdRelaboralEdit" value="0">
        <input type="hidden" id="hdnIdIdeaEdit" value="0">
    </div>
</div>
</div>
<div style="display: none;" class="modal fade bs-example-modal-sm" id="popupClasificacion" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <form class="form-horizontal" id="testForm_perfil" data-toggle="validator" onsubmit="return false;"/>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
                <h4 class="modal-title" id="tituloModal">Clasificaci&oacute;n de la Idea de Negocio</h4>
            </div>
            <div class="modal-body" style="text-align: center">
                <input id="rtClasificacion" class="rating" min="0" max="5" step="0.5" data-size="lg" data-symbol="&#xf005;" data-glyphicon="false" data-rating-class="rating-fa">
            </div>
            <div class="modal-footer">
                <button type="button" id="btnCerrarClasificacion" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-compress"></i> Cerrar</button>
                <button type="button" id="btnGuardarClasificacion" class="btn btn-primary"><i class="fa fa-floppy-o"></i> Guardar Clasificaci&oacute;n</button>
            </div>
            <input id="hdnIdIdeaClasificacion" value="0" type="hidden"/>
            </form>
        </div>
    </div>
</div>
<div style="display: none;" id="divMsjeNotificacionError">
    <div id="divMsjePorError">
    </div>
</div>
<div style="display: none;" id="divMsjeNotificacionWarning">
    <div id="divMsjePorWarning">
    </div>
</div>
<div style="display: none;" id="divMsjeNotificacionSuccess">
    <div id="divMsjePorSuccess">
    </div>
</div>
