<?php
    $anio = substr($datos_personal['fecha_nac'],0,4); 
    $mes = substr($datos_personal['fecha_nac'],5,2); 
    $mes = $mes -1;
    $dia = substr($datos_personal['fecha_nac'],8,2); 
    $fecha = $dia.', '.$mes.', '.$anio;
    $tipoDocs = array("CI" => "Carnet de Identidad",
                      "RUN" => "RUN",
                      "PASAPORTE" => "Pasaporte",
                      "C_EXT" => "Carnet de Extranjero");
    $expedido = array(
                'LP'=>"LP",
                'OR'=>"OR",
                'PT'=>"PT",
                'CB'=>"CB",
                'CH'=>"CH",
                'TJ'=>"TJ",
                'SC'=>"SC",
                'BN'=>"BN",
                'PD'=>"PD",
                'NN' => "");
    $nacionalidad = array(
                "ARGENTINA" => "Argentina(0)",
                "BOLIVIANA" => "Boliviana(o)",
                "BRASILERA" => "Brazileña(o)",
                "CHILENA" => "Chilena(o)",
                "ECUATORIANA" => "Ecuatoriana(o)",
                "PARAGUAYA" => "Paraguaya(o)",
                "PERUANA" => "Peruana(o)");
    $ciudades = array(
                "LA PAZ" => "La Paz",
                "COCHABAMBA" => "Cochabamba",
                "SUCRE" => "Sucre",
                "ORURO" => "Oruro",
                "POTOSI" => "Potosí",
                "SANTA CRUZ" => "Santa Cruz",
                "CERCADO TARIJA" => "Cercado Tarija",
                "TRINIDAD" => "Trinidad",
                "COBIJA" => "Cobija",
                "MONTERO" => "Montero",
                "OPLOCA" => "Oploca",
                "GUATEMALA" => "Ciudad de Guatemala");
    $estado_civil = array(
                "SOLTER@" => "Soltera(o)",
                "CASAD@" => "Casada(o)",
                "DIVORCIAD@" => "Divorciada(o)",
                "VIUD@" => "Viuda(o)");
    $grupo_sanguineo = array(
                "NN" => "Sin Datos",
                "ORH+" => "ORH+",
                "A+" => "A+",
                "B+" => "B+",
                "AB+" => "AB+",
                "ORH-" => "ORH-",
                "A-" => "A-",
                "B-" => "B-",
                "AB-" => "AB-");
    $sexo = array(
                "F" => "femenino",
                "M" => "masculino");
if ($datos_personal['fecha_caducidad']!= ''){
    $datos_personal['fecha_caducidad'] = date ("d-m-Y",strtotime($datos_personal['fecha_caducidad']));
}
    
?>
<input id="vnacionalidad" value="<?php echo $datos_personal["nacionalidad"]; ?>" hidden="hidden">
<input id="vtipo_doc" value="<?php echo $datos_personal["tipo_doc"]; ?>" hidden="hidden">
<input id="vexpd" value="<?php echo $datos_personal["expd"]; ?>" hidden="hidden">
<input id="vlugar_nac" value="<?php echo $datos_personal["lugar_nac"]; ?>" hidden="hidden">
<input id="vfecha_nac" value="<?php echo $datos_personal["fecha_nac"]; ?>" hidden="hidden">
<input id="ve_civil" value="<?php echo $datos_personal["e_civil"]; ?>" hidden="hidden">
<input id="vgrupo_sanguineo" value="<?php echo $datos_personal["grupo_sanguineo"]; ?>" hidden="hidden">
<input id="vgenero" value="<?php echo $datos_personal["genero"]; ?>" hidden="hidden">
<input id="anio" value="<?php echo $anio; ?>" hidden="hidden">
<input id="mes" value="<?php echo $mes; ?>" hidden="hidden">
<input id="dia" value="<?php echo $dia; ?>" hidden="hidden">
<input id="fecha" value="<?php echo $fecha; ?>" hidden="hidden">
<style type="text/css">
        body, html {
            height: 100%;
            padding: 0px;
            margin: 0px;
            width: 100%;
            border: none;
            overflow: hidden;
        }
        .required {
            vertical-align: baseline;
            color: red;
            font-size: 10px;
        }
        .control-label {
            white-space: nowrap;
        }
    </style>
</head>
<body>
    <script type="text/javascript">
        $(document).ready(function () {
            //set
            
            // set jQWidgets Theme to "Bootstrap"
            $.jqx.theme = "bootstrap";
            //$('#sendButton').jqxButton({ height: 25 });
            $('#cancelButton').jqxButton({ height: 25 });
            // create jqxInput widget.
            $('input').jqxInput({ height: 22, width: '100%' });
            $('input').css('margin-top', '5px');
            // create grupo_sanguineo ComboBox.
            // create Accept Terms Checkbox.CI
            //$("#acceptTerms").jqxCheckBox({ width: '100%' });
            // create the Birth Date Calendar.
            //$("#f_nacimiento").jqxDateTimeInput({ enableBrowserBoundsDetection: true, width: '100%', height: 24, formatString:'yyyy-MM-dd' });
            //$("#f_nacimiento").jqxDateTimeInput('setDate',new Date($("#anio").val(),$("mes").val(),$("dia").val()));
            //$("#f_nacimiento").jqxDateTimeInput('setDate',$("#fecha").val());
            // create the Cart Type ComboBox.
            // Create Expiration Date & Year ComboBoxes.
            /*$("#expirationDate").jqxComboBox({ enableBrowserBoundsDetection: true, source: months, selectedIndex: 0, height: 22, width: '100%' });
            $("#expirationYear").jqxComboBox({ enableBrowserBoundsDetection: true, source: years, autoDropDownHeight: true, selectedIndex: 0, height: 22, width: '100%' });*/
            // Create the Form Validator. 
            //$('#form').jqxValidator( { focus: false } );
            /*$('#form').jqxValidator({
                hintType: 'label',
                rules: [
                       { input: '#p_nombre', message: 'El primer nombre es un campo requerido!', action: 'keyup, blur', rule: 'required' },
                       { input: '#p_apellido', message: 'El primer apellido es un campo requerido!', action: 'keyup, blur', rule: 'required' },
                       { input: '#ci', message: 'El número de documento es un campo requerido!', action: 'keyup, blur', rule: 'required' },
                       { input: '#nacionalidad', message: 'La nacionalidad es un campo requerido!', action: 'keyup, blur', rule: 'required' },
                       { input: '#observaciones', message: 'Prueba!', action: 'keyup, blur', rule: 'required' }
                ]
            });*/
            // Validate form.
            $("#cancelButton").click(function () {
                document.location.href = '/personal/listar';
            });
            /*$("#sendButton").click(function () {
                var validationResult = function (isValid) {
                    if (isValid) {
                        $("#form").submit();
                    }
                }
                $('#form').jqxValidator('validate', validationResult);
                if(!$("#p_nombre").val()){
                    alert('Debe ingresar el primer nombre.');
                    return false;
                }
                if(!$("#p_apellido").val()){
                    alert('Debe ingresar el primer apellido.');
                    return false;
                }
                if(!$("#ci").val()){
                    alert('Debe ingresar el documento de identidad.');
                    return false;
                }
                var tipo_doc = $("#tipoDoc").jqxComboBox('getSelectedItem');
                var expedido = $("#expedido").jqxComboBox('getSelectedItem');
                var nacionalidad = $("#nacionalidad").jqxComboBox('getSelectedItem');
                if (nacionalidad == null){
                    alert ('Debe seleccionar una nacionalidad.');
                    return false;
                }
                var l_nacimiento = $("#l_nacimiento").jqxComboBox('getSelectedItem');
                if (l_nacimiento == null){
                    alert ('Debe seleccionar un lugar de nacimiento.');
                    return false;
                }
                var fecha_nac = $('#f_nacimiento').jqxDateTimeInput('getDate');
                var e_civil = $('#estado_civil').jqxComboBox('getSelectedItem');
                if (e_civil == null){
                    alert ('Debe seleccionar un estado civil.');
                    return false;
                }
                var grupo_sanguineo = $('#grupo_sanguineo').jqxComboBox('getSelectedItem');
                var genero = $('#sexo').jqxComboBox('getSelectedItem');//alert(expedido);
            	if (genero == null){
                    alert ('Debe seleccionar sexo de la persona.');
                    return false;
                }
                //var fecha_emi = $('#fecha_emi').jqxDateTimeInput('getDate');
            	var v=$.ajax({
                    	url:'../../personal/save',
                    	type:'POST',
                    	datatype: 'json',
			data:{id:$("#id").val(),p_nombre:$("#p_nombre").val(),s_nombre:$("#s_nombre").val(),t_nombre:$("#t_nombre").val()
                              ,p_apellido:$("#p_apellido").val(),s_apellido:$("#s_apellido").val(),c_apellido:$("#c_apellido").val()
                              ,tipo_doc:tipo_doc.value,ci:$("#ci").val(),expd:expedido.value,num_complemento:$("#num_complemento").val()
                              ,nacionalidad:nacionalidad.value,lugar_nac:l_nacimiento.value,fecha_nac:fecha_nac,e_civil:e_civil.value
                              ,grupo_sanguineo:grupo_sanguineo.value,sexo:genero.value
                              ,id_personas_contacto:$("#id_personas_contactos").val(),direccion_dom:$("#direccion").val()
                              ,telefono_fijo:$("#telefono").val(),celular_per:$("#celular").val(),e_mail_per:$("#email_p").val()
                              ,telefono_inst:$("#tel_inst").val(),telefono_fax:$("#fax").val(),interno_inst:$('#n_interno').val()
                              ,celular_inst:$("#cel_inst").val(),e_mail_inst:$("#email_inst").val(),nit:$("#nit").val()
                              ,num_func_sigma:$("#n_sigma").val(),num_lib_ser_militar:$("#libreta_militar").val(),num_reg_profesional:$("registro_prof").val()
                              ,observacion:$("#observaciones").val(),estado:"0",baja_logica:"0",user_reg_id:"1"},
			success: function(data) { alert (data);
                            var res = jQuery.parseJSON(data);
                            alert(res.msm); 
                            document.location.href = '../../login';
			}, //mostramos el error
			error: function() { 
                            alert('Se ha producido un error Inesperado');
                        }
		});
                //$('#form').jqxValidator('validate');
            });*/
            /*$('#sendButton').on('click', function () {
                //$('#form').jqxValidator( { focus: false } );
                $('#form').jqxValidator('validate');
                //$('#form').jqxValidator( { focus: true } );
            });*/
            // prepare chart data as an array
            var sampleData = [
                    { Day: 'Monday', Running: 30, Swimming: 0, Cycling: 25, Goal: 40 },
                    { Day: 'Wednesday', Running: 30, Swimming: 0, Cycling: 25, Goal: 60 },
                    { Day: 'Friday', Running: 0, Swimming: 20, Cycling: 25, Goal: 50 },
                    { Day: 'Sunday', Running: 20, Swimming: 40, Cycling: 0, Goal: 90 }
            ];
            // prepare jqxChart settings
            var settings = {
                borderLineWidth: 0,
                title: "Fitness & exercise weekly scorecard",
                description: "Time spent in vigorous exercise by activity",
                enableAnimations: true,
                showLegend: true,
                padding: { left: 5, top: 5, right: 5, bottom: 5 },
                titlePadding: { left: 30, top: 0, right: 0, bottom: 10 },
                source: sampleData,
                categoryAxis:
                    {
                        text: 'Category Axis',
                        textRotationAngle: 0,
                        dataField: 'Day',
                        showTickMarks: true,
                        tickMarksInterval: 1,
                        tickMarksColor: '#888888',
                        unitInterval: 1,
                        showGridLines: false,
                        gridLinesInterval: 1,
                        gridLinesColor: '#888888',
                        axisSize: 'auto'
                    },
                colorScheme: 'scheme05',
                seriesGroups:
                    [
                        {
                            type: 'splinearea',
                            valueAxis:
                            {
                                unitInterval: 20,
                                minValue: 0,
                                maxValue: 100,
                                displayValueAxis: false,
                                description: 'Goal in minutes',
                                axisSize: 'auto',
                                tickMarksColor: '#888888'
                            },
                            series: [
                                    { dataField: 'Goal', displayText: 'Personal Goal', opacity: 0.7 }
                            ]
                        },
                        {
                            type: 'stackedcolumn',
                            columnsGapPercent: 100,
                            seriesGapPercent: 5,
                            valueAxis:
                            {
                                unitInterval: 20,
                                minValue: 0,
                                maxValue: 100,
                                displayValueAxis: true,
                                description: 'Time in minutes',
                                axisSize: 'auto',
                                tickMarksColor: '#888888',
                                gridLinesColor: '#777777'
                            },
                            series: [
                                    { dataField: 'Running', displayText: 'Running' },
                                    { dataField: 'Swimming', displayText: 'Swimming' },
                                    { dataField: 'Cycling', displayText: 'Cycling' }
                            ]
                        }
                    ]
            };
            // setup the chart
            //$('#chart').jqxChart(settings);
            // prepare DataTable data.
            var data = new Array();
            var firstNames = ["Nancy", "Andrew", "Janet", "Margaret", "Steven", "Michael", "Robert", "Laura", "Anne"];
            var lastNames = ["Davolio", "Fuller", "Leverling", "Peacock", "Buchanan", "Suyama", "King", "Callahan", "Dodsworth"];
            var titles = ["Sales Representative", "Vice President, Sales", "Sales Representative", "Sales Representative", "Sales Manager", "Sales Representative", "Sales Representative", "Inside Sales Coordinator", "Sales Representative"];
            var k = 0;
            for (var i = 0; i < firstNames.length; i++) {
                var row = {};
                row["firstname"] = firstNames[k];
                row["lastname"] = lastNames[k];
                row["title"] = titles[k];
                data[i] = row;
                k++;
            }
            var source =
            {
                localData: data,
                dataType: "array"
            };
            var dataAdapter = new $.jqx.dataAdapter(source);
            // create DataTable.
            /*$("#dataTable").jqxDataTable(
            {
                width: '100%',
                height: '100%',
                source: dataAdapter,
                sortable: true,
                columns: [
                      { text: 'First Name', dataField: 'firstname', width: '30%' },
                      { text: 'Last Name', dataField: 'lastname', width: '30%' },
                      { text: 'Title', dataField: 'title' }
                ]
            });*/
            $("#myTab").tab();
            $('.box:nth-child(2)').hide();
            $('.box:nth-child(3)').hide();
            $('#myTab a').click(function (e) {
                e.preventDefault();
                $('.box').hide();
                $('#myTab li').removeClass('active');
                var id = $(this).attr('data-tab');
                $("#" + id).show();
                // notifies the widgets that a resize is required and forces a redraw. $.jqx.resize is called for better UX when navigating through tabs.
                $.jqx.resize();
                $(this).parent().addClass('active');
            })
        });
    </script>
    <div style="min-height: 0px; box-shadow: none; -webkit-box-shadow: none;" class="navbar navbar-default " role="navigation">
        <ul id="myTab" style="min-width: 480px; box-shadow: none; -webkit-box-shadow: none; border: none;" class="nav nav-tabs">
            <li style="margin-left: 20px;" class="active"><a data-tab="identificacion" href="#identificacion">Detalles de Identificaci&oacute;n.</a></li>
            <li><a data-tab="contacto" href="#contacto">Datos de Contacto.</a></li>
            <li><a data-tab="alternativo" href="#alternativo">Datos Alternativos.</a></li>
        </ul>
    </div>
    <div class="box-body">
        <div class="row">
            <div class="form-horizontal col-sm-6">
                <h2 style="padding-top: 0px; width: 100%;"><b>Datos de Persona.</b></h2>
            </div>
            <div class="form-horizontal col-sm-6">
                <?php
                if (file_exists('images/personal/'.$datos_personal['ci'].'.jpg')){
                    //echo 'con foto';
                    echo '<img class="img-rounded pull-right img-perfil" src="/images/personal/'.$datos_personal['ci'].'.jpg?'.rand().'" width="128" >';
                } else {
                    //echo 'sin foto';
                    echo '<img class="img-rounded pull-right img-perfil" src="/images/personal/imagen_comodin.png">';
                }
                ?>
            </div>
        </div>
    </div>
    
    <div style="padding-top: 0px; width: 100%; height: 100%;">
        <form class="navbar-form" id="form">
        <div id="identificacion" class="box" style="width: 100%; height: 100%; overflow-x: hidden; border: none;">
            <!--<form class="navbar-form" id="form">-->
                <input id="id" name="id" value="<?php echo $datos_personal['id']; ?>" hidden="hidden">
                <div class="form-horizontal col-sm-6">
                    <div class="form-horizontal">
                        <h2>Detalles de Identificaci&oacute;n:</h2>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label">Nombres :</label>
                        <div class="col-sm-3">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['p_nombre']?></label>
                        </div>
                        <div class="col-sm-3">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['s_nombre']; ?></label>
                        </div>
                        <div class="col-sm-3">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['t_nombre']; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="p_apellido">Apellidos :</label>
                        <div class="col-sm-3">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['p_apellido']; ?></label>
                        </div>
                        <div class="col-sm-3">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['s_apellido'];?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="c_apellido">Apellido de Casada:   </label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['c_apellido']; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="tipoDoc">Tipo de Documento :</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $tipoDocs[$datos_personal['tipo_doc']]; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="ci">N&uacute;mero de Documento :</label>
                        <div class="col-sm-3">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['ci']; ?></label>
                        </div>
                        <div class="col-sm-3">
                            <label class="col-sm-3 control-label"><?php echo $expedido[$datos_personal['expd']]; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="fecha_caducidad">Fecha de Caducidad :</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['fecha_caducidad']; ?></label>
                        </div>
                    </div>
                </div>
                <div class="form-horizontal col-sm-6">
                    <div class="form-horizontal">
                        <h2>Detalles de Gen&eacute;ricos:</h2>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="nacionalidad">Nacionalidad *:</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $nacionalidad[$datos_personal['nacionalidad']]; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="l_nacimiento">Lugar de Nacimiento *:</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $ciudades[$datos_personal['lugar_nac']]; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="f_nacimiento">Fecha de nacimiento *:</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo date('d-m-Y', strtotime($datos_personal['fecha_nac'])); ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="estado_civil">Estado Civil *:   </label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $estado_civil[$datos_personal['e_civil']]; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="grupo_sanguineo">Grupo Sangu&iacute;neo :</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $grupo_sanguineo[$datos_personal['grupo_sanguineo']]; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="sexo">Sexo *:</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $sexo[$datos_personal['genero']]; ?></label>
                        </div>
                    </div>
                </div>
            <!--</form>-->
        </div>
        <div id="contacto" style="width: 100%; height: 100%;" class="box">
            <!--<div style="border: none;" id='dataTable'></div>-->
            <!--<form class="navbar-form" id="form">-->
           
                <div class="form-horizontal col-sm-6">
                    <input id="id_personas_contactos" name="id_personas_contactos" value="<?php echo $id_personas_contactos; ?>" hidden="hidden">
                    <div class="form-horizontal">
                        <h2>Datos de Contacto Personal:</h2>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="direccion">Direcci&oacute;n :</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['direccion_dom']; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="telefono">Tel&eacute;fono :</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['telefono_fijo']; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="celular">Celular :</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['celular_per']; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="email_p">E-mail Personal:</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['e_mail_per']; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="telefono_emerg">Tel&eacute;fono de Emergencia:</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['telefono_emerg']; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="persona_emerg">Persona de Emergencia:</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['persona_emerg']; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="relacion_emerg">Relaci&oacute;n de Parentezco:</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['relacion_emerg']; ?></label>
                        </div>
                    </div>
                </div>
                <div class="form-horizontal col-sm-6">
                    <div class="form-horizontal">
                        <h2>Datos de Contacto Institucional:</h2>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="tel_inst">Tel&eacute;fono Institucional :</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['telefono_inst']; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="fax">FAX :</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['telefono_fax']; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="n_interno">N&uacute;mero Interno :</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['interno_inst']; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="cel_inst">Celular Institucional :   </label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['celular_inst']; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="email_inst">E-mail Institucional:</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['e_mail_inst']; ?></label>
                        </div>
                    </div>
                </div>
            <!--</form>-->
        </div>
        <div id="alternativo" class="box" style="width: 100%; height: 100%; overflow-x: hidden; border: none;">
            <!--<form class="navbar-form" id="form">-->
                <div class="form-horizontal">
                    <h2>Datos alternativos:</h2>
                </div>
                <div class="form-horizontal col-sm-6">
                    <div class="row">
                        <label class="col-sm-3 control-label" for="nit">NIT :</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['nit']; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="n_sigma">Funcionario SIGMA :</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['num_func_sigma']; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="libreta_militar">Libreta Militar :</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label">"<?php echo $datos_personal['num_lib_ser_militar']; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="registro_prof">Registro Profesional :</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['num_reg_profesional']; ?></label>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="observaciones">Observaciones :</label>
                        <div class="col-sm-6">
                            <label class="col-sm-3 control-label"><?php echo $datos_personal['observacion']; ?></label>
                        </div>
                    </div>
                    
                </div>
            <!--</form>-->
        </div>
        <div class="row">
            <div class="col-sm-1">
            </div>
            <div class="col-sm-1">
            </div>
            <div class="col-sm-1">
                <button style="margin-top: 15px;" id="cancelButton" type="button">Volver --></button>
            </div>
        </div>
        </form>
    </div>