
<?php echo $this->tag->form("tipo/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("tipo", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create tipo</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="tipo">Tipo</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("tipo", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
