<style type="text/css">
        body, html {
            height: 100%;
            padding: 0px;
            margin: 0px;
            width: 100%;
            border: none;
            overflow: hidden;
        }
        .required {
            vertical-align: baseline;
            color: red;
            font-size: 10px;
        }
        .control-label {
            white-space: nowrap;
        }
    </style>
</head>
<body>
    <script type="text/javascript">
        $(document).ready(function () {
            //set
            
            // set jQWidgets Theme to "Bootstrap"
            $.jqx.theme = "bootstrap";
            $('#sendButton').jqxButton({ height: 25 });
            // create jqxInput widget.
            $('input').jqxInput({ height: 22, width: '100%' });
            $('input').css('margin-top', '5px');
            // create countries array for the Countries ComboBox.
            var nacionalidad = [
                { value: "AR", label: "Argentina(0)" },
                { value: "BO", label: "Boliviana(o)" },
                { value: "BR", label: "Brazileña(o)" },
                { value: "CL", label: "Chilena(o)" },
                { value: "EC", label: "Ecuatoriana(o)" },
                { value: "PY", label: "Paraguaya(o)" },
                { value: "PE", label: "Peruana(o)" }
            ];
            var ciudades = [
                { value: 0, label: "La Paz" },
                { value: 1, label: "Cochabamba" },
                { value: 2, label: "Sucre" },
                { value: 3, label: "Oruro" },
                { value: 4, label: "Potosí" },
                { value: 5, label: "Santa Cruz" },
                { value: 6, label: "Tarija" },
                { value: 7, label: "Trinidad" },
                { value: 8, label: "Cobija" }
            ];
            // create Countries ComboBox.
            $("#nacionalidad").jqxComboBox({ enableBrowserBoundsDetection: true, autoDropDownHeight: true, promptText: "Seleccione una nacionalidad", source: nacionalidad, height: 22, width: '100%' });
            // create ciudades ComboBox.
            $("#l_nacimiento").jqxComboBox({ enableBrowserBoundsDetection: true, autoDropDownHeight: true, promptText: "Seleccione una ciudad", source: ciudades, height: 22, width: '100%' });
            var estado_civil = [
                { value: 0, label: "Soltera(o)" },
                { value: 1, label: "Casada(o)" },
                { value: 2, label: "Divorciada(o)" },
                { value: 3, label: "Viuda(o)" },
            ];
            // create estado_civil ComboBox.
            $("#estado_civil").jqxComboBox({ enableBrowserBoundsDetection: true, autoDropDownHeight: true, promptText: "Seleccione una opción", source: estado_civil, height: 22, width: '100%' });
            var grupo_sanguineo = [
                { value: 0, label: "ORH+"},
                { value: 1, label: "A+"},
                { value: 2, label: "B+"},
                { value: 3, label: "AB+"},
                { value: 4, label: "ORH-"},
                { value: 5, label: "A-"},
                { value: 6, label: "B-"},
                { value: 7, label: "AB-"},
            ];
            // create grupo_sanguineo ComboBox.
            $("#grupo_sanguineo").jqxComboBox({ enableBrowserBoundsDetection: true, autoDropDownHeight: true, promptText: "Seleccione una opción", source: grupo_sanguineo, height: 22, width: '100%' });
            var sexo = [
                {value: 0, label: "femenino"},
                {value: 1, label: "masculino"}
            ];
            // create grupo_sanguineo ComboBox.
            $("#sexo").jqxComboBox({ enableBrowserBoundsDetection: true, autoDropDownHeight: true, promptText: "Seleccione una opción", source: sexo, height: 22, width: '100%' });
            // create Accept Terms Checkbox.
            //$("#acceptTerms").jqxCheckBox({ width: '100%' });
            // create the Birth Date Calendar.
            $("#f_nacimiento").jqxDateTimeInput({ enableBrowserBoundsDetection: true, width: '100%', height: 24, formatString:'yyyy-MM-dd' });
            // create the Cart Type ComboBox.
            var tipoDocs = [{ value: "1", label: "Carnet de Identidad" }, { value: "2", label: "RUN" }, { value: "3", label: "Pasaporte" }, { value: "4", label: "Carnet de Extranjero" }];
            $("#tipoDoc").jqxComboBox({ enableBrowserBoundsDetection: true, selectedIndex: 0, autoDropDownHeight: true, promptText: "Tipo Documento:", source: tipoDocs, width: '100%', height: 22 });
            /*var months = [
               { value: "01", label: "01 - January" },
               { value: "02", label: "02 - February" },
               { value: "03", label: "03 - March" },
               { value: "04", label: "04 - April" },
               { value: "05", label: "05 - May" },
               { value: "06", label: "06 - June" },
               { value: "07", label: "07 - July" },
               { value: "08", label: "08 - August" },
               { value: "09", label: "09 - September" },
               { value: "10", label: "10 - October" },
               { value: "11", label: "11 - November" },
               { value: "12", label: "12 - December" }
            ];
            var years = [
                { value: "2014", label: "2014" },
                { value: "2015", label: "2015" },
                { value: "2016", label: "2016" },
                { value: "2017", label: "2017" },
                { value: "2018", label: "2018" },
                { value: "2019", label: "2019" },
                { value: "2020", label: "2020" }
            ];*/
            // Create Expiration Date & Year ComboBoxes.
            /*$("#expirationDate").jqxComboBox({ enableBrowserBoundsDetection: true, source: months, selectedIndex: 0, height: 22, width: '100%' });
            $("#expirationYear").jqxComboBox({ enableBrowserBoundsDetection: true, source: years, autoDropDownHeight: true, selectedIndex: 0, height: 22, width: '100%' });*/
            // Create the Form Validator. 
            //$('#form').jqxValidator( { focus: false } );
            $('#form').jqxValidator({
                hintType: 'label',
                rules: [
                       { input: '#p_nombre', message: 'El primer nombre es un campo requerido!', action: 'keyup, blur', rule: 'required' },
                       { input: '#p_apellido', message: 'El primer apellido es un campo requerido!', action: 'keyup, blur', rule: 'required' },
                       { input: '#ci', message: 'El número de documento es un campo requerido!', action: 'keyup, blur', rule: 'required' },
                       { input: '#nacionalidad', message: 'La nacionalidad es un campo requerido!', action: 'keyup, blur', rule: 'required' },
                       { input: '#observaciones', message: 'Prueba!', action: 'keyup, blur', rule: 'required' }
                ]
            });
            // Validate form.
            $("#sendButton").click(function () {
                var validationResult = function (isValid) {
                    if (isValid) {
                        $("#form").submit();
                    }
                }
                $('#form').jqxValidator('validate', validationResult);
                var fecha_apr = $('#fecha_apr').jqxDateTimeInput('getDate');
            	var fecha_emi = $('#fecha_emi').jqxDateTimeInput('getDate');
            	var v=$.ajax({
                    	url:'../../personal/save/',
                    	type:'POST',
                    	datatype: 'json',
			data:{id:$("#id").val(),tipo_resolucion:$("#tipo_resolucion").val(),numero_res:$("#numero_res").val(),fecha_apr:fecha_apr,fecha_emi:fecha_emi},
			success: function(data) { cargar(); //alert(data); 
			}, //mostramos el error
			error: function() { alert('Se ha producido un error Inesperado'); }
		});
                //$('#form').jqxValidator('validate');
            });
            /*$('#sendButton').on('click', function () {
                //$('#form').jqxValidator( { focus: false } );
                $('#form').jqxValidator('validate');
                //$('#form').jqxValidator( { focus: true } );
            });*/
            // prepare chart data as an array
            var sampleData = [
                    { Day: 'Monday', Running: 30, Swimming: 0, Cycling: 25, Goal: 40 },
                    { Day: 'Wednesday', Running: 30, Swimming: 0, Cycling: 25, Goal: 60 },
                    { Day: 'Friday', Running: 0, Swimming: 20, Cycling: 25, Goal: 50 },
                    { Day: 'Sunday', Running: 20, Swimming: 40, Cycling: 0, Goal: 90 }
            ];
            // prepare jqxChart settings
            var settings = {
                borderLineWidth: 0,
                title: "Fitness & exercise weekly scorecard",
                description: "Time spent in vigorous exercise by activity",
                enableAnimations: true,
                showLegend: true,
                padding: { left: 5, top: 5, right: 5, bottom: 5 },
                titlePadding: { left: 30, top: 0, right: 0, bottom: 10 },
                source: sampleData,
                categoryAxis:
                    {
                        text: 'Category Axis',
                        textRotationAngle: 0,
                        dataField: 'Day',
                        showTickMarks: true,
                        tickMarksInterval: 1,
                        tickMarksColor: '#888888',
                        unitInterval: 1,
                        showGridLines: false,
                        gridLinesInterval: 1,
                        gridLinesColor: '#888888',
                        axisSize: 'auto'
                    },
                colorScheme: 'scheme05',
                seriesGroups:
                    [
                        {
                            type: 'splinearea',
                            valueAxis:
                            {
                                unitInterval: 20,
                                minValue: 0,
                                maxValue: 100,
                                displayValueAxis: false,
                                description: 'Goal in minutes',
                                axisSize: 'auto',
                                tickMarksColor: '#888888'
                            },
                            series: [
                                    { dataField: 'Goal', displayText: 'Personal Goal', opacity: 0.7 }
                            ]
                        },
                        {
                            type: 'stackedcolumn',
                            columnsGapPercent: 100,
                            seriesGapPercent: 5,
                            valueAxis:
                            {
                                unitInterval: 20,
                                minValue: 0,
                                maxValue: 100,
                                displayValueAxis: true,
                                description: 'Time in minutes',
                                axisSize: 'auto',
                                tickMarksColor: '#888888',
                                gridLinesColor: '#777777'
                            },
                            series: [
                                    { dataField: 'Running', displayText: 'Running' },
                                    { dataField: 'Swimming', displayText: 'Swimming' },
                                    { dataField: 'Cycling', displayText: 'Cycling' }
                            ]
                        }
                    ]
            };
            // setup the chart
            //$('#chart').jqxChart(settings);
            // prepare DataTable data.
            var data = new Array();
            var firstNames = ["Nancy", "Andrew", "Janet", "Margaret", "Steven", "Michael", "Robert", "Laura", "Anne"];
            var lastNames = ["Davolio", "Fuller", "Leverling", "Peacock", "Buchanan", "Suyama", "King", "Callahan", "Dodsworth"];
            var titles = ["Sales Representative", "Vice President, Sales", "Sales Representative", "Sales Representative", "Sales Manager", "Sales Representative", "Sales Representative", "Inside Sales Coordinator", "Sales Representative"];
            var k = 0;
            for (var i = 0; i < firstNames.length; i++) {
                var row = {};
                row["firstname"] = firstNames[k];
                row["lastname"] = lastNames[k];
                row["title"] = titles[k];
                data[i] = row;
                k++;
            }
            var source =
            {
                localData: data,
                dataType: "array"
            };
            var dataAdapter = new $.jqx.dataAdapter(source);
            // create DataTable.
            /*$("#dataTable").jqxDataTable(
            {
                width: '100%',
                height: '100%',
                source: dataAdapter,
                sortable: true,
                columns: [
                      { text: 'First Name', dataField: 'firstname', width: '30%' },
                      { text: 'Last Name', dataField: 'lastname', width: '30%' },
                      { text: 'Title', dataField: 'title' }
                ]
            });*/
            $("#myTab").tab();
            $('.box:nth-child(2)').hide();
            $('.box:nth-child(3)').hide();
            $('.box:nth-child(4)').hide();
            $('#myTab a').click(function (e) {
                e.preventDefault();
                $('.box').hide();
                $('#myTab li').removeClass('active');
                var id = $(this).attr('data-tab');
                $("#" + id).show();
                // notifies the widgets that a resize is required and forces a redraw. $.jqx.resize is called for better UX when navigating through tabs.
                $.jqx.resize();
                $(this).parent().addClass('active');
            })
        });
    </script>
    <div style="min-height: 0px; box-shadow: none; -webkit-box-shadow: none;" class="navbar navbar-default " role="navigation">
        <ul id="myTab" style="min-width: 480px; box-shadow: none; -webkit-box-shadow: none; border: none;" class="nav nav-tabs">
            <li style="margin-left: 20px;" class="active"><a data-tab="identificacion" href="#identificacion">Detalles de Identificaci&oacute;n.</a></li>
            <li><a data-tab="generico" href="#generico">Detalles Gen&eacute;ricos.</a></li>
            <li><a data-tab="contacto" href="#contacto">Datos de Contacto.</a></li>
            <li><a data-tab="alternativo" href="#alternativo">Datos Alternativos.</a></li>
        </ul>
    </div>
    <h2 style="padding-top: 0px; width: 100%;"><b>Nuevo Registro de Persona.</b></h2>
    <h6><b>NOTA: </b>Los datos precedidos de asterisco son requerido des manera obligatoria(*).</h6>
    
    <div style="padding-top: 0px; width: 100%; height: 100%;">
        <form class="navbar-form" id="form">
        <div id="identificacion" class="box" style="width: 100%; height: 100%; overflow-x: hidden; border: none;">
            <!--<form class="navbar-form" id="form">-->
                <div class="form-horizontal">
                    <h2>Detalles de Identificaci&oacute;n:</h2>
                </div>
                <div class="form-horizontal col-sm-6">
                    <div class="row">
                        <label class="col-sm-3 control-label" for="p_nombre">Nombres *:</label>
                        <div class="col-sm-3">
                            <input placeholder="Primer Nombre" id="p_nombre" name="p_nombre" value="" />
                        </div>
                        <div class="col-sm-3">
                            <input placeholder="Segundo Nombre" id="s_nombre" name="s_nombre" value="" />
                        </div>
                        <div class="col-sm-3">
                            <input placeholder="Tercer Nombre" id="t_nombre" name="t_nombre" value="" />
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="p_apellido">Apellidos *:</label>
                        <div class="col-sm-3">
                            <input placeholder="Primer Apellido" id="p_apellido" name="p_apellido" value="" />
                        </div>
                        <div class="col-sm-3">
                            <input placeholder="Segundo Apellido" id="s_apellido" name="s_apellido" value="" />
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="c_apellido">Apellido de Casada:   </label>
                        <div class="col-sm-6">
                            <input placeholder="Apellido de Casada" name="c_apellido" value="" />
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="tipoDoc">Tipo de Documento :</label>
                        <div class="col-sm-6">
                            <div style="margin-top: 5px;" id="tipoDoc"></div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="ci">N&uacute;mero de Documento *:</label>
                        <div class="col-sm-6">
                            <input placeholder="Número Documento" id="ci" name="ci" value="" />
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="expd">N&uacute;mero Complemento :</label>
                        <div class="col-sm-6">
                            <input placeholder="123" id="expd" name="expd" value="" />
                        </div>
                    </div>
                    <!--<div>
                        <label class="col-sm-4 control-label" for="birthDate">Birth Date</label>
                        <div class="col-sm-8">
                            <div style="margin-top: 5px;" id="birthDate" name="birthDate"></div>
                        </div>
                    </div>-->
                </div>
            <!--</form>-->
        </div>
        <div id="generico" class="box" style="width: 100%; height: 100%; overflow: hidden; border: none;">
           <!--<form class="navbar-form" id="form">-->
                <div class="form-horizontal">
                    <h2>Detalles de Gen&eacute;ricos:</h2>
                </div>
                <div class="form-horizontal col-sm-6">
                    <div class="row">
                        <label class="col-sm-3 control-label" for="nacionalidad">Nacionalidad *:</label>
                        <div class="col-sm-6">
                            <div style="margin-top: 5px;" id="nacionalidad" on></div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="l_nacimiento">Lugar de Nacimiento *:</label>
                        <div class="col-sm-6">
                            <div style="margin-top: 5px;" id="l_nacimiento" on></div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="f_nacimiento">Fecha de nacimiento *:</label>
                        <div class="col-sm-6">
                            <div style="margin-top: 5px;" id="f_nacimiento" name="f_nacimiento"></div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="estado_civil">Estado Civil *:   </label>
                        <div class="col-sm-6">
                            <div style="margin-top: 5px;" id="estado_civil" on></div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="grupo_sanguineo">Grupo Sangu&iacute;neo :</label>
                        <div class="col-sm-6">
                            <div style="margin-top: 5px;" id="grupo_sanguineo"></div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="sexo">Sexo *:</label>
                        <div class="col-sm-6">
                            <div style="margin-top: 5px;" id="sexo"></div>
                        </div>
                    </div>
                </div>
            <!--</form>-->
        </div>
        <div id="contacto" style="width: 100%; height: 100%;" class="box">
            <!--<div style="border: none;" id='dataTable'></div>-->
            <!--<form class="navbar-form" id="form">-->
                <div class="form-horizontal col-sm-6">
                    <div class="form-horizontal">
                        <h2>Datos de Contacto Personal:</h2>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="direccion">Direcci&oacute;n :</label>
                        <div class="col-sm-6">
                            <input placeholder="Direcci&oacute;n" id="direccion" name="direccion" value="" />
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="telefono">Tel&eacute;fono :</label>
                        <div class="col-sm-6">
                            <input placeholder="N&uacute;mero de Tel&eacute;fono" id="telefono" name="telefono" value="" />
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="celular">Celular :</label>
                        <div class="col-sm-6">
                            <input placeholder="N&uacute;mero de Celular" id="celular" name="celular" value="" />
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="email_p">E-mail Personal:</label>
                        <div class="col-sm-6">
                            <input placeholder="Correo electr&oacute;nico" id="email_p" name="email_p" value="" />
                        </div>
                    </div>
                </div>
                <div class="form-horizontal col-sm-6">
                    <div class="form-horizontal">
                        <h2>Datos de Contacto Institucional:</h2>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="tel_inst">Tel&eacute;fono Institucional :</label>
                        <div class="col-sm-6">
                            <input placeholder="Tel&eacute;fono Institucional" id="tel_inst" name="tel_inst" value="" />
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="fax">FAX :</label>
                        <div class="col-sm-6">
                            <input placeholder="Tel&eacute;fono FAX" id="fax" name="fax" value="" />
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="n_interno">N&uacute;mero Interno :</label>
                        <div class="col-sm-6">
                            <input placeholder="N&uacute;mero Interno" id="n_interno" name="n_interno" value="" />
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="cel_inst">Celular Institucional :   </label>
                        <div class="col-sm-6">
                            <input placeholder="Celular Institucional" id="cel_inst" name="cel_inst" value="" />
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="email_inst">E-mail Institucional:</label>
                        <div class="col-sm-6">
                            <input placeholder="Correo electr&oacute;nico" id="email_inst" name="email_inst" value="" />
                        </div>
                    </div>
                </div>
            <!--</form>-->
        </div>
        <div id="alternativo" class="box" style="width: 100%; height: 100%; overflow-x: hidden; border: none;">
            <!--<form class="navbar-form" id="form">-->
                <div class="form-horizontal">
                    <h2>Datos alternativos:</h2>
                </div>
                <div class="form-horizontal col-sm-6">
                    <div class="row">
                        <label class="col-sm-3 control-label" for="nit">NIT :</label>
                        <div class="col-sm-6">
                            <input placeholder="NIT" id="nit" name="nit" value="" />
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="nit">Funcionario SIGMA :</label>
                        <div class="col-sm-6">
                            <input placeholder="C&oacute;digo funcionario SIGMA" id="n_sigma" name="n_sigma" value="" />
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="libreta_militar">Libreta Militar :</label>
                        <div class="col-sm-6">
                            <input placeholder="C&oacute;digo Libreta Militar" id="libreta_militar" name="libreta_militar" value="" />
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="registro_prof">Registro Profesional :   </label>
                        <div class="col-sm-6">
                            <input placeholder="N&uacute;mero de Registro Profesional" id="registro_prof" name="registro_prof" value="" />
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label" for="observaciones">Observaciones :</label>
                        <div class="col-sm-6">
                            <input placeholder="Observaciones" id="observaciones" name="observaciones" value="" />
                        </div>
                    </div>
                    
                </div>
            <!--</form>-->
        </div>
        <div class="row">
            <div class="col-sm-1">
            </div>
            <div class="col-sm-1">
                <button style="margin-top: 15px;" id="sendButton" type="button">Grabar</button>
            </div>
        </div>
        </form>
    </div>