<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9"> </html><![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8" />
        <title>Sistema de Seguimiento a Procesos Administrativos</title>
        <meta name="description" content="ProUI is a Responsive Admin Dashboard Template created by pixelcave and published on Themeforest. This is the demo of ProUI! You need to purchase a license for legal use!" />
        <meta name="author" content="pixelcave" />
        <meta name="robots" content="noindex, nofollow" />
        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0" />
        <link rel="shortcut icon" href="./img/favicon.ico" />
        <link rel="apple-touch-icon" href="./img/icon57.png" sizes="57x57" />
        <link rel="apple-touch-icon" href="./img/icon72.png" sizes="72x72" />
        <link rel="apple-touch-icon" href="./img/icon76.png" sizes="76x76" />
        <link rel="apple-touch-icon" href="./img/icon114.png" sizes="114x114" />
        <link rel="apple-touch-icon" href="./img/icon120.png" sizes="120x120" />
        <link rel="apple-touch-icon" href="./img/icon144.png" sizes="144x144" />
        <link rel="apple-touch-icon" href="./img/icon152.png" sizes="152x152" />
        <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/assets/css/plugins.css" />
        <link rel="stylesheet" href="/assets/css/main.css" />
        <link rel="stylesheet" href="/assets/css/themes.css" />
        <script src="/assets/js/vendor/modernizr-2.7.1-respond-1.4.2.min.js"></script>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head>
    <body>
        <div id="login-background">
            <img src="/assets/img/placeholders/headers/login_header.jpg" alt="Login Background" class="animation-pulseSlow" />
        </div>
        <?php echo $this->view->getContent(); ?>
        <script src="../../../ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script>!window.jQuery && document.write(unescape('%3Cscript src="/assets/js/vendor/jquery-1.11.0.min.js"%3E%3C/script%3E'));</script>
        <script src="/assets/js/vendor/bootstrap.min.js"></script>
        <script src="/assets/js/plugins.js"></script>
        <script src="/assets/js/app.js"></script>
        <script src="/assets/js/pages/login.js"></script>
        <script>$(function() {
                Login.init();
            });
        </script>        
    </body>
</html>